### ISSUE TITLE
How to draw maps with manim?

### ISSUE THREAD

**Issue by haohello** [ManimCommunity/manim#1033]
## Description of proposed feature

I find it very helpful to draw maps and do the GIS illustration with manim.  Do you have any ideas how to accomplish this with manim?

**Comment by MrMallIronmaker** [comment]
I ended up rewriting a lot of the SVG engine for this very reason - I wanted an SVG of the US states for a video I was working on. If you can export your data to an SVG file, that is one good option. Because I work with spatial data using R, I'd probably use ggplot or some other R library to make the file. I would think that my approach isn't ideal though.

As for more domain-aware methods, like handling different GIS files and e.g. different projection options, I'd suggest a plugin for manim.

What kind of data are you working with and how do you envision coding and animating it?

**Comment by jsonvillanueva** [comment]
@haohello I think this is a discussion (not an issue) best suited for our [Discord server](https://discord.com/invite/mMRrZQW). Additionally, you may wish to see this [tweet on twitter](https://twitter.com/i/status/1367583109449797633) (source code [here](https://github.com/ManimCommunity/manim-tweets/blob/main/2021_03_04_v0.4.0_release.py)) in which I adapted an SVG file to draw a world map.

At the heart of GIS, this involves manual work in both creating/formatting the SVG file to work with Manim (support will only get better), and accessing the SVG elements submojects and coloring them appropriately. Please feel free to discuss this further on Discord.
