### ISSUE TITLE
Usage of the pathlib package to manage folders

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#110]
I just skimmed https://github.com/ManimCommunity/manim/issues/66 and thought that the [pathlib](https://docs.python.org/3/library/pathlib.html) module (python standard library) can be useful to manage the folder structure.

Also, this could help to run manim in an IDE without the necessity to use the terminal.
A script can look like this:
```py
from manim import *

class SimpleDot(Scene):
    def construct(self):
        dot = Dot()
        self.add(dot)

from pathlib import Path
if __name__ == "__main__":
    script = f"{Path(__file__).resolve()}"
    os.system(f"manim -s -p -c 'BLACK' --video_dir ~/Downloads/ " + script + " " + "SimpleDot")
```

**Comment by leotrs** [comment]
If I understand correctly, you are suggesting two different things. One is to use `pathlib` instead of `os.path` for certain operations, for example in #66. The other one is to recommend the use of this `os.system` line in scene files in case the user wants to skip the CLI and work fully from an IDE. I think this are two entirely different things. The second one doesn't need `pathlib` at all. So I think we should discuss them in separate issues. 

FWIW, I'm all for using `pathlib` instead of `os.path` as long as it's clear what are the benefits we gain from that. And as for adding this `os.system` line, I'm not sure what is the best way to implement this. Perhaps we could recommend this to users in the (soon-to-exist) tutorial. This is not really a change in the codebase.

**Comment by kolibril13** [comment]
Yes, you are right, these are two different things.
The second one was only to give a further example.
Focusing on the first use case for #66 , this could make the code a little prettier.

**Comment by leotrs** [comment]
I'd be happy to see a PR migrating our use of os.path to using pathlib :)

**Comment by leotrs** [comment]
@kolibril13 any progress? ;)

**Comment by kolibril13** [comment]
Hi @leotrs , the last hour I tried to understand the result of all the discussions, but I failed. I made a new issue to understand what we want to do now https://github.com/ManimCommunity/manim/issues/204
