### ISSUE TITLE
Cannot install manim in editable mode

### ISSUE THREAD

**Issue by adamryczkowski** [ManimCommunity/manim#1116]
After cloning the manim, according to the documentation (https://docs.manim.community/en/v0.4.0/installation/for_dev.html, "Manim Installation For Developers with pip") I tried to
```
$ pip install -e <path to manim repo root>
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/adam/manim
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

After reading through the github issues (like https://github.com/ManimCommunity/manim/pull/754 ) I found out, that in theory the project should be installable in edit mode by using some "poetry" tool like this:

```
$ cd /home/adam/manim
$ poetry build 
Building manim (0.4.0)
  - Building sdist
  - Built manim-0.4.0.tar.gz
  - Building wheel
  - Built manim-0.4.0-py3-none-any.whl
$ pip install -e .
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/adam/manim
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

## Expected behavior: 
Ability to somehow install manim in editable mode. I am tracking a bug and want to quickly be able to troubleshoot it in-place. 

## System specifications

OS Ubuntu 20.04 64bit
16GB RAM
Python 3.8.5

**Comment by naveen521kk** [comment]
You can run `poetry install` after installing poetry. You don't need to run `poetry build` and https://github.com/ManimCommunity/manim/pull/754 is misleading because it is for someone who can't use poetry.

See the discussion on poetry's thread https://github.com/python-poetry/poetry/discussions/1135#discussioncomment-145756

Also, see out https://docs.manim.community/en/v0.4.0/installation/for_dev.html#installing-manim-using-poetry

**Comment by adamryczkowski** [comment]
Here is the solution:

1. Install the poetry (using `pip` is enough)
2. change directory to the pulled root of the pulled manim repository.
3.  `poetry install` there.

Poetry installs packages in editable mode
