### ISSUE TITLE
Add a decorator to `override_animation` in Mobject

### ISSUE THREAD

**Issue by jsonvillanueva** [ManimCommunity/manim#1336]
## Description of proposed feature

As per [the discussion](https://github.com/ManimCommunity/manim/pull/1225#issuecomment-812216240) resulting in #1225 being closed, there's interest in providing Mobject specific animations to override Animation.

## How can the new feature be used?

Per @behackl suggestion, the decorator would be used like:

```python
    @override_animation(Create)
    def _custom_create(self, *args, **kwargs):
        # build a custom create animation
        return my_custom_animation
```
to override the way the class calls the animation (in this case Create).

## Additional comments

https://github.com/ManimCommunity/manim/pull/1225#issuecomment-812216240

**Comment by huguesdevimeux** [comment]
👍🏻 , I like the idea !

**Comment by AntonBallmaier** [comment]
I would like to work on this one :)

**Comment by AntonBallmaier** [comment]
@huguesdevimeux could you assign me to the issue?

**Comment by AntonBallmaier** [comment]
I am unsure where I should put the code. I tend towards animation/override_animation.py

**Comment by huguesdevimeux** [comment]
> I am unsure where I should put the code. I tend towards animation/override_animation.py

My first thought would be for animation.py.

**Comment by AntonBallmaier** [comment]
Now that I have looked into it a bit I feel like we should abandon this idea. Yes, it seems like a nice idea at first, but it is not only very unpythonic, it also requires a Lot of workarounds.

If we have a look at the following code example, what exactly would you expect to happen:

```py
class SomeMobject(Mobject):

    @override_animation(Create)
    def _create(self, **kwargs):
        return AnyOtherAnimation(**kwargs)

mob = SomeMobject()
create = Create(mob)
``` 
What is the type of create? Is it `Create` or `AnyOtherAnimation`?  It can only be `Create` since it is created using `Create()`. However, when played as an animations it needs to behave like an `AnyOtherAnimation`. So when playing an animation you would need to check, whether it is overwritten - and if so simply ignore the actual animation? That seems really strange to me. Also, should `_create` be passed all the arguments passed to `Create`? In custom animations other arguments might be fitting.

On top of that, coding a decorator like this would actually require additional initialization code to be run after all classes have been fully loaded. It would be convoluted and about as far from "pythonic" as one might get. Yes, it would be nice to have a feature like this, but it isn't really more than a bit of syntactic sugar. I don't think that's worth it.

I propose a different approach mostly based on the documentation:  
Custom Animations are simply implemented as methods returning Animations (like ManimBanner.create).
When annotating such a method with `@animation_substitute(AnyAnimation)` (or a similar name)  a special info box will be added to the docs of that method referencing the Animation it should be used instead of. Optionally we could also list it in a new section on the documentations page of `AnyAnimation`.

**Comment by friedkeenan** [comment]
> It can only be Create since it is created using Create()

This isn't true, as `Animation.__new__` can return any object, and that object only gets passed along to `__init__` if the returned object is an instance of `cls` (the first argument to `__new__`).

```py
>>> class Test:
...    def __new__(cls):
...        return 1
...
>>> Test()
1
```

**Comment by AntonBallmaier** [comment]
Ohhh, I didn't know about `__new__` and it didn't come up in my research :D This opens new possibilities :D
