### ISSUE TITLE
Need more examples for the documents 

### ISSUE THREAD

**Issue by cckk4467** [ManimCommunity/manim#1367]
@Nikhil0504 
as you ask, I pin you here XD
We need to complete docs with more examples
docs like [this](https://docs.manim.community/en/latest/reference/manim.animation.indication.html#module-manim.animation.indication)

ideal of docs should be like [this](https://docs.manim.community/en/latest/reference/manim.animation.fading.html#module-manim.animation.fading)
(may be not that much ideal, but a good display of animations will help a lot)
Appreciate your contribution in advance XD

**Comment by Nikhil0504** [comment]
I did one PR for checking. #1366 check and tell if it’s fine

**Comment by jsonvillanueva** [comment]
Currently, ManimCommunity contributors are not given Triage permissions... although this may change in the future. This issue seems apt for multiple assignees. It'd be good to have a checklist of which modules need examples and who is being assigned to them so that work can be distributed with redundancy.

**Comment by AntonBallmaier** [comment]
I looked into the indication module and feel like there are quite a few problems with the classes defined there:

- Naming inconsistencies (for example `ShowCreationThenDestruction` instead of `CreateThenUncreate`)
- Generally useless classes (why would you use 
`AnimationOnSurroundingRectangle(mob, AnyAnimation)` instead of 
`AnyAnimation(SurroundingRectangle(mob))` ?)
- Overall somewhat confusing

Therefor I propose we delay the creation of example animations until after we decided how to change the interfaces. I will create an Issue with my suggestions shortly.

**Comment by behackl** [comment]
This issue doesn't really have an explicit goal; we are continuously working on improving the documentation. Closing.
