### ISSUE TITLE
Clipping of rate function values in animations cause wiggle not to work properly

### ISSUE THREAD

**Issue by PhilippImhof** [ManimCommunity/manim#158]
Reported by @wschutzer in the discord channel, initially opened as https://github.com/3b1b/manim/issues/1140

Using code from 06/10, I could not get the following simple wiggle scene to render properly:

```python
class test(Scene):
    def construct(self):
        dot = Dot(color=YELLOW)
        self.add(dot)
        self.play(dot.shift, RIGHT, rate_func=lambda t: wiggle(t,6),run_time=5)
        self.wait(1)
```

The movement would occur in one direction as expected but not on the other. After digging into the code, I found the following lines in manimlib/animation/animation.py:

```python
def get_sub_alpha(self, alpha, index, num_submobjects):
        # TODO, make this more understanable, and/or combine
        # its functionality with AnimationGroup's method
        # build_animations_with_timings
        lag_ratio = self.lag_ratio
        full_length = (num_submobjects - 1) * lag_ratio + 1
        value = alpha * full_length
        lower = index * lag_ratio
        return np.clip((value - lower), 0 1) # <---- could this be -1 instead of 0?
```

Since the wiggle function outputs values in the [-1, 1] interval, I fail to see how it's supposed to work with the above clipping in place. While I understand that it's supposed to be a safety net against wild user-provided rate functions, I believe it's better to extend the clipping to the [-1, 1] interval.

**Comment by huguesdevimeux** [comment]
For me, this is impossible, the values must be between 0 and 1

The whole system on which manim is built is around alpha values, that are typically between 0 and 1. These values are used to interpolate objects during the animations. Every animation has an `interpolate_submobject `method that uses alpha values. If the value is, let's say, 0, then the object is at its starting state, and if it is 1, then at its final state. 
Example: Here some alpha values when running `Write `animation at 15 fps : 
```
0.0
0.06666666666666667
0.13333333333333333
0.2
0.26666666666666666
0.3333333333333333
0.4
0.4666666666666667
0.5333333333333333
0.6
0.6666666666666666
0.7333333333333333
0.8
0.8666666666666667
0.9333333333333333
```
You see, there are 15 values, for each of the 15 frames. (Note: when rendering only the last frame, there will be only one alpha value, 1.0 (because we only want the last frame). 

But then how is this related to the `rate_func`? Well, the rate function determines the alpha values.
See L. 111 animations.py : 
`self.interpolate_mobject(self.rate_func(alpha))`. 

Thus, in my example, I used the `linear ``rate_func`. I could have used -x, then, the object would have disappeared instead of appearing (btw that is what is used in `Uncreate`, IIRC). You can of course create your own rate_func.

The wiggle rate func is used only one time: l. 166 indication.py
```
         submobject.rotate(
            wiggle(alpha, self.n_wiggles) * self.rotation_angle,
            about_point=self.get_rotate_about_point()
        )
```
As you can see, it passed to `submobject.rotate` as ... an angle. So its ok if the value is negative, because it is not an `interpolate` method. But this is very misleading, that's true.

**Comment by wschutzer** [comment]
To me it makes sense to standardize the t parameter between 0 and 1, but the output clipping is probably unnecessary or that decision could perhaps better be left to the programmer to decide.  Anyway, that simple change, `return np.clip((value - lower), -1, 1)` worked great for me, and as far as I can tell did not break anything else since virtually all rate functions return positive values anyway.

**Comment by huguesdevimeux** [comment]
But did you try to interpolate an animation with a negative alpha? What does happen?

**Comment by wschutzer** [comment]
> But did you try to interpolate an animation with a negative alpha? What does happen?

Try this:
```
class test(Scene):
    def construct(self):
        dot = Dot(color=YELLOW)
        self.add(dot)
        self.play(dot.shift, RIGHT, rate_func=lambda t: wiggle(t,6),run_time=5)
        self.wait(1)
```
I believe it works at it's supposed to after you change the said clipping.

**Comment by huguesdevimeux** [comment]
This example works as the negatives values are clipped and changed to 0 (as you said).
But without clipping, what does happen?

**Comment by wschutzer** [comment]
It works as expected. The dot bonces left and right about the center.

**Comment by huguesdevimeux** [comment]
It works thanks to in `straight_path`, l11 in `paths.py`. `stright_path` (used in `mobject.shift`) basically constructs the straight path (yes, really) and constructs the intermediate points depending on the alpha given (alpha obtained with the rate_func - so in this case, with wiggles and without clipping, negatives values), with `interpolate `function. So if the alpha is negative, then `interpolate` will return a set of point "behind" the path, which is what you want but is -in my opinion, of course- a bug.

By the way, I don't know if changing the clipping will cause that much damage, since a lot of animations (probably all of them) use `integer_interpolate`, (l.47, `bezizer.py`)to construct their points, which, by essence, has got a clipping functionality.

**Comment by leotrs** [comment]
@huguesdevimeux with all the craziness happening recently, it is my impression that this one might have been fixed. Yes? No?

**Comment by huguesdevimeux** [comment]
> @huguesdevimeux with all the craziness happening recently, it is my impression that this one might have been fixed. Yes? No?

I don't know. To me, there was nothing to fix in particular, but as this has been quiet for 3 weeks I think this is fair to close it.
