### ISSUE TITLE
NumberPlane and/or other objects not positioned at the center of screen since 0.6.0

### ISSUE THREAD

**Issue by ksachdeva** [ManimCommunity/manim#1624]
## Description of bug / unexpected behavior
A circle or rectangle object does not seem to be positioned at the center in NumberPlace since 0.6.0 release.

## Expected behavior
Both NumberPlane and Circle (or other Mobject) should be aligned at the center of the screen by default

## How to reproduce the issue

```py
class TestCentering(Scene):
    def construct(self):
        plane = NumberPlane(axis_config={"include_numbers": True})
        circle = Circle(radius=1.)
        self.add(plane, circle)
```

## Additional media files

This is the image generated by 0.5.0 (Expected Behavior)

![TestCentering_ManimCE_v0 5 0](https://user-images.githubusercontent.com/127006/120800984-35526500-c506-11eb-95b8-339ff7664ae7.png)

This is the image generated by 0.6.0 and 0.7.0 versions (Not Expected Behavior)

![TestCentering_ManimCE_v0 6 0](https://user-images.githubusercontent.com/127006/120801023-426f5400-c506-11eb-8ebc-fe03bc67f631.png)

## System specifications

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)): macOS 11.3.1
- RAM:
- Python version (`python/py/python3 --version`):3.7
- Installed modules (provide output from `pip list`):
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by hydrobeam** [comment]
The issue seems to be that, when centering the plane mobject at some point during the creation process, the numbers are also included and the overall plane is skewed. The same problem exists for `Axes` where the lines are shifted away from the center. The fix would be to have the lines of the plane handled seperately and centered without including the numbers. I've gotten this solution to work and I'll PR it when it's more polished
