### ISSUE TITLE
Init `Polygon` with vertices

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1645]
Currently, it is not possible to simply call `Polygon()` to get a polygon. This is possible for other Mobjects, and should be possible here as well.
I suggest the following init parameters:
```py
class Example(Scene):
    def construct(self):
        position_list = [
        rotate_vector(UP,0),  
        rotate_vector(UP,1*TAU/6),  
        rotate_vector(UP,2*TAU/6),   
        rotate_vector(UP,3*TAU/6), 
        rotate_vector(UP,4*TAU/6),   
        rotate_vector(UP,5*TAU/6), 
        ]
        p = Polygon(*position_list,color= YELLOW)
        self.add(p)
```
![image](https://user-images.githubusercontent.com/44469195/120931943-0d285900-c6f4-11eb-9b7e-23e7f05355e7.png)

**Comment by PhotonSpheres** [comment]
I agree with that. Do you think this should also be possible with, e.g., `Angle()`? And stuff like `MatrixMobject()`?

**Comment by friedkeenan** [comment]
I don't think it necessarily makes sense to make it so every mobject can be constructed with no arguments. Something that is more abstract like `Polygon` should require explication from the user imo. If you want something more concrete, you can do `RegularPolygon()` just fine, which incidentally will give you the hexagon you propose but blue.

**Comment by kolibril13** [comment]
Currently, calling `Polygon` with no parameter gives an error:
![image](https://user-images.githubusercontent.com/44469195/121131799-917ff680-c830-11eb-905f-217a601f43ed.png)
I don't like this too much. I suggest the following:
In case that `Polygon` is called with no parameters, `RegularPolygon` gets called, together with the warning:
"""
Waring, Polygon was initialized without the parameter `vertices`, so `RegularPolygon` is called instead. 
Please  provide the `vertices` parameter.
"""

**Comment by friedkeenan** [comment]
like I said, I believe `Polygon` itself is too abstract for it to be a benefit to be constructed with no arguments. If a user wants a regular polygon, they can use `RegularPolygon`, otherwise it's likely a mistake that they didn't pass any arguments to `Polygon`, but even if it's intentional, it's not very readable. Why *specifically* do you want it to be constructable with no arguments?

**Comment by kolibril13** [comment]
> Why specifically do you want it to be constructable with no arguments?
For new users is might be confusing that Dot(), Circle(), Triangle() etc. can be constructed without arguments, but Polygon can not.
I would be fine when we adjust the error message in a way that it saies:
"
Error, Polygon was initialized without the parameter vertices, please provide vertices, or use  `RegularPolygon` that initializes a Hexagon by default.
"

**Comment by friedkeenan** [comment]
I agree that the error message could be more descriptive; in fact after #1651 the error message is a bit better:
```
    first_vertex, *vertices = vertices
ValueError: not enough values to unpack (expected at least 1, got 0)
```

I don't agree that it would be meaningfully confusing for new users that they can't just construct a `Polygon` with no arguments; some things just require input from the user, that's not strange. With things like `Dot` and `Circle`, etc. it can be reasonably assumed that if the user isn't specifying `radius` and whatnot, they don't care about the radius, and just want a generic circle. The difference is that a circle's shape doesn't depend on the radius, the radius just scales the circle; a polygon's shape however very much depends on its vertices, and to be fair a regular polygon's shape does depend on how many sides it has, but *much* less than a polygon depends on its vertices. And if a user is using `Polygon` instead of `RegularPolygon` (or another `Polygon` subclass), that should signal that they care about the individual vertices, and so should specify them.

**Comment by kolibril13** [comment]
Okay, I am convinced now, thanks for your changes in #1651.
I am closing this issue then.
