### ISSUE TITLE
Have the `Developer Installation` docs point to Poetry's installation page.

### ISSUE THREAD

**Issue by hydrobeam** [ManimCommunity/manim#1840]
## Enhancement proposal

Instead of manually maintaining the installation page, in case poetry changes its API, we should just point to their docs for installation instead. 

A link to 
```
https://python-poetry.org/docs/master/#installation
```
can replace
![image](https://user-images.githubusercontent.com/70682032/127456594-314c6e6e-a462-44ba-96e7-f4cbdf7eb84f.png)

## Additional comments

Motivated by poetry's changed installation command which caused an insallation issue.

**Comment by kadatatlukishore** [comment]
hey @hydrobeam , Can I work on this ?

**Comment by Darylgolden** [comment]
Of course! Assigning you.

**Comment by kadatatlukishore** [comment]
Thanks @Darylgolden. I should be replacing the entire thing as shown in screenshot to a link right ?

**Comment by Darylgolden** [comment]
> 
> 
> Thanks @Darylgolden. I should be replacing the entire thing as shown in screenshot to a link right ?

Yes, with some phrasing changes if necessary

**Comment by kadatatlukishore** [comment]
## For Developers with Poetry (Recommended)


Please follow the link [docs on installation - python poetry](https://python-poetry.org/docs/master/#installation)


# INSTEAD OF

## For Developers with Poetry (Recommended)

Poetry can be easily installed in any OS by running the following command:

### Linux / OSX / BashOnWindows install instructions

`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python`


### Windows PowerShell install instructions

`(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python`

**Poetry can be installed by other ways also, such as with** `pip`. 
          
See (https://python-poetry.org/docs/#alternative-installation-methods-not-recommended). 
          

If you are using MacOS with the Homebrew package manager, you can also install 
          poetry with `brew install poetry`.

It will add it to `PATH` variable automatically. In order to make sure you have poetry installed correctly, try running:

`poetry --version`


**You may need to restart your shell in order for the changes to take effect**

See the [docs on installation python poetry for more information](https://python-poetry.org/docs/).

**Comment by kadatatlukishore** [comment]
This would be fine right @Darylgolden

**Comment by Darylgolden** [comment]
> 
> 
> This would be fine right @Darylgolden

There are still some changes I would make. Make a PR with your initial changes and we can review them and directly make changes there; it's easier that way.
