### ISSUE TITLE
Specify package versions in requirements.txt

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#19]
Currently, `requirements.txt` does not specify versions.

**Comment by eulertour** [comment]
We actually did this because specifying versions caused things to break over time. It probably could have been avoided if someone regularly updated the versions, but then there's the question of when to do it. The laziest answer is probably 'as soon as something breaks' but it's probably not the best.

**Comment by leotrs** [comment]
I think the right answer is "whenever we want to make a release".

**Comment by eulertour** [comment]
In that case we should table this until we have a release, since we don't know how long that could be.

**Comment by leotrs** [comment]
Fair! I'll add it to the project board then.

**Comment by leotrs** [comment]
For clarity, this will be done only once we are ready to release a new version of manim.
