### ISSUE TITLE
Understanding the output folder structure of manim

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#204]
Hi,
It is amazing to see this progress in this repo after being inactive for a while.
Now, I wanted to have a look at the folder structure of manim, and here I have some questions:
One way to define the folder structure is like this:
## A)
```python
from manim import *

class HiThere(Scene):
    def construct(self):
        dot = Dot()
        self.add(dot)
        self.wait(1)

from pathlib import Path
if __name__ == "__main__":
    script = f"{Path(__file__).resolve()}"
    download_folder= str(Path.home() / "Downloads")
    os.system(f"manim  -l -s -p -c 'BLACK' --media_dir {download_folder}  {script} ")
```
And another like this
## B)
```python
from manim import *

class HiThere(Scene):
    def construct(self):
        dot = Dot()
        self.add(dot)
        self.wait(1)

from pathlib import Path
if __name__ == "__main__":
    script = f"{Path(__file__).resolve()}"
    os.system(f"manim  -l -s -p -c 'BLACK' --config_file '/home/hendrik/projects/manim-community/manim/kolibril.cfg' " + script )
```
where I have the file "kolibril.cfg" and the option:
```sh
# --media_dir
media_dir = /home/hendrik/Downloads/
```
Now my question:
Is this not some kind of redundancy, that we should remove?

I think only defining everything in the cfg file should be enough, and then we don't need the media_dir flag anymore.

# Further point:

In the ".cfg" files, there are the options :
```sh
# # --video_dir
video_dir = " "

# # --tex_dir
tex_dir = " "

# # --text_dir
text_dir = " "
```
But I think, they don't have any effect.
I saw a lot of discussions going on about this, and I am now quite confused of what we want to have.
Can maybe someone give an overview of how we want to handle this? :)

**Comment by leotrs** [comment]
> Is this not some kind of redundancy, that we should remove? 
> I think only defining everything in the cfg file should be enough, and then we don't need the media_dir flag anymore.

If I understand correctly, your question is about using the `--media_dir` flag directly as a CLI argument versus setting it in a user config fie and specifying that file through the command line. The answer is that these two are not redundant. For example, you can specify both: `manim ... --media_dir=<some_dir> --config_file?<some_file>`. In this case, the config will be initialized using the cascading config file system and then the `config["media_dir"]` option will be overriden by your CLI argument `--media_dir`. The point of the cascading file system is that there are many sources of config options, with different priorities. `config.py` parses all of these sources and puts them in a single place, the global `config` dict. The priorities, from lowest to highest, are as follows: the library-wide `default.cfg`, then the user-wide `manim.cfg` in the user directory, if it exists, then the folder-wide `manim.cfg` if it exists, and then the CLI arguments. Each file/flag overrides all of the ones previous.

So to answer your question: the fact that config options can be specified with CLI flags as well as through the `.cfg` files is intentional. I wouldn't call it "redundant", but actually "flexible".

 
> # Further point:
> In the ".cfg" files, there are the options :
> 
> ```shell
> # # --video_dir
> video_dir = " "
> 
> # # --tex_dir
> tex_dir = " "
> 
> # # --text_dir
> text_dir = " "
> ```
> 
> But I think, they don't have any effect.
> I saw a lot of discussions going on about this, and I am now quite confused of what we want to have.
> Can maybe someone give an overview of how we want to handle this? :)

Yes, these are useless for now. As per previous discussions #66, it was decided that the default behavior would be to keep everything under `media_dir` with the exact same folder structure. That's why the only directory you can set right now is `media_dir`, and you get a `videos`, `tex`, `text` folders inside of it.

In the future, if anyone wants to, they can implement an alternative folder structure. For example, the way I would do it is as follows. If you want complete control over video/tex/text_dir with three separate CLI flags, then you can make use of the (currently useless) config options you have highlighted in `default.cfg`. You would do so by changing the code in `config.py` which reads in those flags and sets `config["videos_dir"]` and the others.

An alternative way of doing it is by exposing a single flag, for example `--folder_structure=default` or `--folder_structure=custom`. The first case ("default") would just do what manim is doing already and no further changes would be necessary. But in the second case ("custom"), you can have `config.py` read in `--media_dir` and use that to set the others with your own internal logic. An easy way of doing this is to create a new section in the config file that is used in `config.py` to override the [CLI] section, for example, this is how the `-t` and `--dry_run` flags are handled, and you can read the code for them to see how this is done.

If you decide to do either of these, please make sure to NOT CHANGE the `default.cfg` file. Changing it is going to change the default behavior of the whole library for all users. Changes to this file have to be discussed thoroughly with the whole dev team.

**Comment by kolibril13** [comment]
Thanks for this nice explanation, that is really well thought out!
When I type `manim -h` I get currently this output:
```
positional arguments:
  file                  path to file holding the python code for the scene
  scene_names           Name of the Scene class you want to see

optional arguments:
  -h, --help            show this help message and exit
  -o OUTPUT_FILE, --output_file OUTPUT_FILE
                        Specify the name of the output file, if it should be
                        different from the scene class name
  -p, --preview         Automatically open the saved file once its done
  -f, --show_file_in_finder
                        Show the output file in finder
  -q, --quiet           Quiet mode
  --sound               Play a success/failure sound
  --leave_progress_bars
                        Leave progress bars displayed in terminal
  -a, --write_all       Write all the scenes from a file
  -w, --write_to_movie  Render the scene as a movie file
  -s, --save_last_frame
                        Save the last frame (and do not save movie)
  -g, --save_pngs       Save each frame as a png
  -i, --save_as_gif     Save the video as gif
  -c COLOR, --color COLOR
                        Background color
  --background_opacity BACKGROUND_OPACITY
                        Background opacity
  --media_dir MEDIA_DIR
                        directory to write media
  --tex_template TEX_TEMPLATE
                        Specify a custom TeX template file
  --dry_run             Do a dry run (render scenes but generate no output
                        files)
  -t, --transparent     Render to a movie file with an alpha channel
  -l, --low_quality     Render at low quality (for fastest rendering)
  -m, --medium_quality  Render at medium quality (for much faster rendering)
  -e, --high_quality    Render at high quality (for slightly faster rendering)
  -k, --fourk_quality   Render at 4K quality (slower rendering)
  -r RESOLUTION, --resolution RESOLUTION
                        Resolution, passed as "height,width"
  -n FROM_ANIMATION_NUMBER, --from_animation_number FROM_ANIMATION_NUMBER
                        Start rendering not from the first animation, butfrom
                        another, specified by its index. If you passin two
                        comma separated values, e.g. "3,6", it will endthe
                        rendering at the second value
  --config_file CONFIG_FILE
                        Specify the configuration file

Made with ❤  by the manim community devs
```

So it would be probably we should add in the end something like:
"Specify the configuration file (Arguments in this document will have higher priority then phrased arguments)."

Tomorrow I will start the implementation of the both options "--folder_structure=default" and "--folder_structure=custom"

**Comment by leotrs** [comment]
> So it would be probably we should add in the end something like:
> "Specify the configuration file (Arguments in this document will have lower priority then phrased arguments)."

Feel free to include this in your PR ;)

Closing this now.
