### ISSUE TITLE
line_spacing paramter in Text should be float

### ISSUE THREAD

**Issue by Morinator** [ManimCommunity/manim#2110]
**Text("test", line_spacing=1.3)** gets a warning in PyCharm for using the wrong data-type, but floating-point numbers work fine.

I guess the type hint in the **Text** class should be *float* instead of *int*.

**Comment by wiltzutm** [comment]
So I quickly checked this in the codebase and it's also relevant (I think) for the Paragraph class as well. This leads to the conclusion that it isn't just a change in type hints.

The original intent seems that the numbers really are int (I have no idea why tho?) and there's a lot of if clauses testing for a case where line_spacing == -1 (eg. adjust automatically). At least all those would have to be changed to if line_spacing < 0. But to be honest, it would be nice to know the reasoning for the original intent of using ints in the first place...

**Comment by LemmaEOF** [comment]
Looking into it, there's no reason for it to *not* be a float. [`line_spacing` gets multiplied by `font_size`](https://github.com/ManimCommunity/manim/blob/main/manim/mobject/svg/text_mobject.py#L475-L480), which itself is a float, and multiplying an int and a float will *always* result in a float.

**Comment by wiltzutm** [comment]
Ah ok. I don't know did we misunderstand each other somehow @LemmaEOF , but my comment was more about the semantics because obviously the intent of the original programmer was to use ints so that he/she may check the default value integer -1 for example in the class Text initialization:
```python
 if self.line_spacing == -1:
      self.line_spacing = (
          self._font_size + self._font_size * DEFAULT_LINE_SPACING_SCALE
       )
else:
    self.line_spacing = self._font_size + self._font_size * self.line_spacing
```
Also I'm assuming that the scale should never be strictly negative.

What I would do is either change the initialization like this:
```python
def __init__(self, ..., line_spacing: float = DEFAULT_LINE_SPACING_SCALE, ...):
```
and remove the line_spacing checking inside the initializer altogether (and everywhere else where it's used). In this scenario the global constant type should be float as well...

Or if you really wan't to hold on to the default value checks, then change the type into Optional[float] and do the checking with ```python 
if line_space is None
```
 instead of
```python
if line_space == -1
```
These are potentially breaking changes if some user has explicitly set the line_spacing value to -1 in ones code...which would be odd, but never underestimate the human tendency to do stupid things. ;)

**Comment by wiltzutm** [comment]
Oh yeah and maybe assert that the line_spacing is positive.

**Comment by wiltzutm** [comment]
if you wan't to support both int and float eg. numbers and ensure that there won't be any breaking changes then substitute all the default value checks with
```python
if self.line_spacing < 0.0
```
and set the type as Union[float, int] or something similar...

**Comment by LemmaEOF** [comment]
Ah yeah I see, I think I did misunderstand slightly. Ultimately, due to how python type hints aren't actually enforced at all (and are purely there for linters to analyze), checking equality to -1 should still work just fine if you pass the literal value in. I think just changing the type hints should be fine enough, since the docs say to pass in -1 for auto-spacing.

**Comment by behackl** [comment]
Semantically, I'd really like if we could change the default value for automatic line spacing from `-1` (???) to `None`. Seems like this is a different and somewhat more involved issue.

Also, `Union[float, int]` is covered by simply putting `float` as the type hint (see <https://www.python.org/dev/peps/pep-0484/#the-numeric-tower>).

**Comment by wiltzutm** [comment]
> Ah yeah I see, I think I did misunderstand slightly. Ultimately, due to how python type hints aren't actually enforced at all (and are purely there for linters to analyze), checking equality to -1 should still work just fine if you pass the literal value in. I think just changing the type hints should be fine enough, since the docs say to pass in -1 for auto-spacing.

Yes you are right that functionally it indeed works anyways.
