### ISSUE TITLE
Mobject align_to bug

### ISSUE THREAD

**Issue by netwizard22** [ManimCommunity/manim#2379]
## Description of bug / unexpected behavior

Example provided in [link](https://docs.manim.community/en/latest/_modules/manim/mobject/mobject.html#Mobject.align_to) does not work as intended
```py
Examples:
mob1.align_to(mob2, alignment_vect = RIGHT) moves mob1
horizontally so that it's center is directly above/below
the center of mob2
```

## Expected behavior

Mobject does not get aligned at all.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
    def construct(self):
        n = NumberPlane()
        s = Square(stroke_width = 10, stroke_color = RED).shift(DL * 4)
        s2 = Square(stroke_width = 10).shift(UR)
        s = s.align_to(s2, alignment_vect = RIGHT)
        self.add(n, s, s2)
```

</details>

## Additional media files

![scriptoutput](https://user-images.githubusercontent.com/96273664/146478932-128657c5-ab4f-412a-a74a-c8eddb9c95c7.png)
<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by behackl** [comment]
Thank you for reporting!

The current implementation does not use `alignment_vect` at all, so to close this issue two things have to happen:

- [ ] A discussion about the intended use of this parameter -- it is not really clear to me what it is even supposed to do. Should it specify the vector along which the mobject is moved in order to be aligned? Or should it specify the edge of the mobject that should be aligned?
- [ ] The implementation has to be adapted and the documentation updated accordingly.

**Comment by netwizard22** [comment]
It seems that this issue is a duplicate of [this](https://github.com/ManimCommunity/manim/issues/113).
