### ISSUE TITLE
Mobject Ordering Regression in 0.15

### ISSUE THREAD

**Issue by sudgy** [ManimCommunity/manim#2585]
Consider the following scene:

```python
class Test(Scene):
    def construct(self):
        a = Square(color = RED)
        b = Square(color = BLUE)
        b.shift(RIGHT)
        self.add(a)
        self.wait()
        self.bring_to_back(b)
        self.play(FadeIn(b))
        self.wait()
```

In 0.14, this is the output:

https://user-images.githubusercontent.com/20936595/156047966-0ba1256e-bfef-41f0-99ed-8a8a5278be6e.mp4

In 0.15, this is the output:

https://user-images.githubusercontent.com/20936595/156047888-01c82af9-5c90-41bb-9944-72eb8197a9c8.mp4

As you can see, the blue square is correctly drawn behind the red one in 0.14, but in 0.15, the blue square is drawn on top.

**Comment by behackl** [comment]
Bisecting shows that this was introduced via #2396. This should be fixed by checking whether the mobject belonging to an animation with `introducer=True` set (like `FadeIn`) has already been added to the scene.

There is one workaround I can offer: in your example, either put
```py
self.play(FadeIn(b), introducer=False)
```
or, more verbose,
```py
anim = FadeIn(b)
anim.introducer = False
self.play(anim)
```
(the obvious `FadeIn(b, introducer=False)` unfortunately won't work due to the keyword argument not being propagated correctly.)
