### ISSUE TITLE
Documentation of NumberPlane should be clearer about length of x_range and y_range

### ISSUE THREAD

**Issue by jamesjcai** [ManimCommunity/manim#2657]
## Description of bug / unexpected behavior

From the given example here,
https://docs.manim.community/en/stable/reference/manim.mobject.graphing.coordinate_systems.NumberPlane.html#manim.mobject.graphing.coordinate_systems.NumberPlane

the x_range and y_range have been set up but the output figure still shows the ranges of default setting.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
Paste your code here.
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by dawnsqrl** [comment]
It seems that the default value for `x_range` and `y_range` just happen (or are specially designed to) coincide with the display scale of a standard 1080p image. Use `number_plane.scale(0.2)` and the full plane becomes visible.

![NumberPlaneScale_ManimCE_v0.15.1](https://user-images.githubusercontent.com/35942162/161896687-bea90394-1e16-46b8-aaf2-a84fb16582de.png)

I'm not sure if it is necessary to integrate an "auto-scale" feature into `NumberPlane`'s constructor, or whether the mentioned example should be updated to clear out such ambiguities.

**Comment by jamesjcai** [comment]
Thank you. It works. However, if I add 
         arrow = Arrow(ORIGIN, [1, 5, 0], buff=0)
and then
        number_plane=number_plane.scale(0.2)
        self.add(number_plane, arrow)
There is still problem as the arrow won't be scaled.

**Comment by behackl** [comment]
Thanks for reporting! I think it would be worth to...

1. update the example in the documentation and remove the specified x and y ranges (to illustrate default usage)
2. add a second example image in which perhaps two different number planes are constructed where both x/y ranges and the corresponding lengths are set explicitly,
3. The note-block should be clarified to read something along the lines of "If the keyword arguments `x_length` and `y_length` are not set explicitly, they are determined automatically such that one unit on the axis is one Manim unit long."

Might be a good issue to tacke for new contributors. :-)

Regarding the arrow not being scaled: this is expected, if you want that to happen, add the arrow as a submobject to the plane instead of a mobject of the scene (`number_plane.add(arrow)`).

**Comment by Charis02** [comment]
Hi,

I would like to work on this issue.

**Comment by behackl** [comment]
> Hi,
> 
> I would like to work on this issue.

Sure, go ahead!
