### ISSUE TITLE
FadeOut does not work if an updater is added to Mobject 

### ISSUE THREAD

**Issue by mginesi** [ManimCommunity/manim#2736]
## Description of bug / unexpected behavior
On manim v0.15.2 Objects with an updater attached do not fade out (nor in) but disappear (or appear) suddenly.
(Un)create works properly though.
I attach a minimal example

## How to reproduce the issue

```py
 from manim import *

class fadeout_error(Scene):
    def construct(self):
        s = ValueTracker(0)
        txt = MathTex(r"\text{e}^{\mathbf{i}\pi}+1=0").move_to((s.get_value(),0,0))
        txt.add_updater(lambda m : m.become(MathTex(r"\text{e}^{\mathbf{i}\pi}+1=0").move_to((s.get_value(),0,0))))
        self.play(Write(txt))
        self.play(s.animate.set_value(1))
        self.play(FadeOut(txt), run_time=2) # FadeOut doesn't work
        # self.play(Uncreate(txt), run_time=2) # Uncreate works
        # self.play(txt.animate.set_opacity(0), run_time=2) # animate.set_opacity doesn't work
        return super().construct()
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

https://user-images.githubusercontent.com/30355881/170229504-cb575947-3e01-43ec-99ca-fd85bdb76454.mp4

</details>

## System specifications

<details><summary>System Details</summary>

- OS Linux Mint 20.3 x86_64
- RAM: 16GB
- Python version (`python/py/python3 --version`): 3.8.10

**Comment by MrDiver** [comment]
The problem that you have here is that you have conflicting updates with the mobject. On one hand youre setting the `opacity` value in the FadeIn/FadeOut Animation but on the other hand you create a new MathTex Mobject every frame in the updater. The problem that you have here is that the Animation is probably ran before the updater so that the change of the opacity is not applied to the newly created Mobject in that frame. And the only thing that is left is then is the appearance or disappearance of the Mobject. Because of the `add` and `remove` calls for Introducer and Remover Animations.

```py
txt.add_updater(lambda m : m.move_to((s.get_value(),0,0)))
```
The solution is to just not create a new mobject every frame!

**Comment by mginesi** [comment]
Thanks for the reply.
I understand that for this example I should use other methods (shift or move_along_path, for instance).
But what if I MUST use an updater and then FadeOut? I encountered this problem using FunctionGraph, in which the domain has to change in the scene, and I cannot fadeout the graph at the end. I have no idea how to achieve a "moving domain" without an updater.

**Comment by behackl** [comment]
Is it absolutely necessary that updating and fading out happens simultaneously? You could suspend the updater while running the animation otherwise, via `your_mobject.suspend_updating()`.

The other thing you could try is change how your updater is written, and use a two-line function
```py
def updater(mob, dt):
    target_opacity = mob.stroke_opacity
    mob.become(...)
    mob.set_opacity(target_opacity)
```
if you know that it is specifically the opacity you need to update.

**Comment by MrDiver** [comment]
```py
class Test(Scene):
    def construct(self):
        phase_shift = ValueTracker(0)
        cos_func = FunctionGraph(
            lambda t: np.cos(t+phase_shift.get_value()) + 0.5 * np.cos(7 * (t+phase_shift.get_value())) + (1 / 7) * np.cos(14 * (t+phase_shift.get_value())),
            color=RED,
        )
        cos_func.add_updater(lambda m: m.set(points=np.zeros((0,3))).generate_points())
            
        self.add(cos_func)
        self.play(phase_shift.animate.set_value(np.pi))
        cos_func.suspend_updating()
        self.play(FadeOut(cos_func))

```

Because there are enough workarounds for this i think this can savely be closed!
