### ISSUE TITLE
LaTeX compilation error: Paragraph ended before \align* was complete.

### ISSUE THREAD

**Issue by DiscreteTom** [ManimCommunity/manim#2829]
## Description of bug / unexpected behavior

MathTex matrix not working when using groups.

## Expected behavior

```py
MathTex(r'\begin{bmatrix}  {{a}} \\ {{b}} \end{bmatrix}')
```

Should render to 

$$
\begin{bmatrix}  {{a}} \\ {{b}} \end{bmatrix}
$$

## How to reproduce the issue

```py
t = MathTex(r'\begin{bmatrix}  {{a}} \\ {{b}} \end{bmatrix}')
```

## Logs

```
                    ERROR    LaTeX compilation error: Paragraph ended before \align* was complete.   tex_file_writing.py:279
                    ERROR    Context of error:                                                       tex_file_writing.py:313                             -> \end{align*}

                             \end{document}

                    ERROR    A group of double braces, {{ ... }}, was detected in                         tex_mobject.py:291                             your string. Manim splits TeX strings at the double
                             braces, which might have caused the current
                             compilation error. If you didn't use the double brace
                             split intentionally, add spaces between the braces to
                             avoid the automatic splitting: {{ ... }} --> { { ... } }.
```

**Comment by behackl** [comment]
This is essentially the same problem that causes the compilation to fail when splitting the expression in the numerator of a `\frac`, manim does not know how to cleanly treat the situation when environments are not closed properly. (And this is the case here because in order to determine which glyphs should be part of which submobject, manim tries to render the subexpressions individually.)

The code that handles some special strings when splitting is here: https://github.com/ManimCommunity/manim/blob/b58a574bc22964514406a41cfd9ad619a32ca9d7/manim/mobject/text/tex_mobject.py#L142

Unfortunately, I don't have a good suggestion of a workaround for you: either don't use split strings with custom environments, or if you'd like to experiment, you could try to modify the library code and add `"bmatrix"` to the list of contexts that currently only has `"array"` in it.

**Comment by DiscreteTom** [comment]
Thanks @behackl .
I also found https://github.com/3b1b/manim/issues/872
Now I'm using `Matrix` instead of `MathTex` to create matrix and it works fine.

**Comment by yusancky** [comment]
I met the same problem when using enviroment `cases`. What should I do? 😞

$$
\begin{cases}
a &= &b \\
c &= &d
\end{cases}
$$

Maybe I can solve it by replacing it with three parts( $\\{$, $a=b$, $c=d$). But It's a bit of a hassle. 🤔

**Comment by behackl** [comment]
> I met the same problem when using enviroment `cases`. What should I do? 😞

Check https://docs.manim.community/en/stable/faq/help.html or share your logs here.

**Comment by yusancky** [comment]
> > I met the same problem when using enviroment `cases`. What should I do? 😞
> 
> Check https://docs.manim.community/en/stable/faq/help.html or share your logs here.

Thanks very much. 👍

But to replace it with three parts is enough for me to use. 😄
