### ISSUE TITLE
Create a conda-forge recipe for the installation

### ISSUE THREAD

**Issue by pavelzw** [ManimCommunity/manim#2862]
## Description of proposed feature
It would be nice if the installation was easier to use. My suggestion would be to create a conda-forge recipe for manim that contains all the dependencies and installation instructions. 

## How can the new feature be used?
When using conda recipes, one would only need to execute `conda install -c conda-forge manim` to install manim and all its dependencies instead of following several steps for the installation which also differ depending on the operating system.

**Comment by pavelzw** [comment]
I looked a bit into it and the most problematic dependency is [skia-pathops](https://github.com/fonttools/skia-pathops). It seems like a nightmare to port it into conda-forge since it completely redefines the build process and doesn't use standard tooling. 

The most feasible way would probably be to get rid of this dependency/rewrite the setup part of skia-pathops but this will probably take a lot of time...
See [fonttools/skia-pathops (issue 56)](https://github.com/fonttools/skia-pathops/issues/56) and [conda-forge/staged-recipes (pr 19143)](https://github.com/conda-forge/staged-recipes/pull/19143).

**Comment by MrDiver** [comment]
I would like to see information about, why the installation was not easy to use and on which operating system you had problems.

**Comment by pavelzw** [comment]
I didn't have any problems, but I believe it can be made more accessible by integrating it into conda. Then, one wouldn't need to worry about additional dependencies. Also, you bloat your system when installing other dependencies like pango or scipy [directly](https://docs.manim.community/en/stable/installation/macos.html#required-dependencies) on your system instead of a virtual environment.

**Comment by MrDiver** [comment]
But that seems more like a general issue with python which every user has to deal with no matter the library or program. I don't really see how an extra installation of something else solves accessibility. It just makes it even more steps. We might think about putting it in a virtual environment if that is a possibility with the default python packaging system.
Else I don't see why we should start maintaining another way of installing manim, because 5 are already enough in my opinion.

And yes it would be really nice if python could finally deal with dependencies in the installation.

But there are too many inexperienced users which are not even familiar with the normal python world. And i don't think conda will solve accessibility for them because conda will have as many issues as the other installation method in one form or another.

(Just my opinion maybe the other devs have a different take on that)

But yeah, adding more steps doesn't make it easier. It doesn't solve ffmpeg and latex too.

**Comment by pavelzw** [comment]
> It doesn't solve ffmpeg and latex too.

It doesn't solve LaTeX, that's right. But [ffmpeg](https://anaconda.org/conda-forge/ffmpeg) can just be added as another conda dependency for manim that gets installed automatically. 

One advantage of using conda would be that you just need to reference `conda install -c conda-forge manim` instead of all the different installation methods because conda does the platform-dependent stuff automatically for you.
