### ISSUE TITLE
Choose which version of Python to install manimce to with chocolatey

### ISSUE THREAD

**Issue by JamieMair** [ManimCommunity/manim#2873]
## Description of proposed feature

When I install manimce via chocolatey:
```bash
choco install manimce
```
It finds the default Python 3.8 on my system. Is there a way to select the interpreter one would like to install to? For example, installing to an anaconda 3 environment:

```bash
conda activate myenv
choco install manimce
```

## How can the new feature be used?

Install to the version of python currently aliased to "python" in your shell (so current anaconda environment), or be able to specify which python interpreter to install to:

```
choco install manime
.
.
.
Select interpreter to install to (default: C:\Python38\python.exe): <ENTER YOUR PATH HERE>
```

**Comment by naveen521kk** [comment]
> It finds the default Python 3.8 on my system. Is there a way to select the interpreter one would like to install to? For example, installing to an anaconda 3 environment:

Why don't use `pip` or `conda` if you want to install manim inside your virtual environment?

Chocolatey is a *system* level package manager and finding the python executable it installed seems right. It queries the registry for finding the correct python executable rather than searching in `$PATH`. Chocolatey is for system-level things and shouldn't be used for virtual environments, so I don't see the use case of this feature. Also, chocolatey is mostly for the ease of installation and for people who don't have previous programming experience to get started with manim easily; so making it work is actually more important. If manim was installed in a virtual environment it'll *not* be working when the environment is deactivated and this could *confuse* new users.

You should consider using other installation means, like `pip`, when using a virtual environment.
