### ISSUE TITLE
Documentation error in `manim.mobject.types.image_mobject`

### ISSUE THREAD

**Issue by igreat** [ManimCommunity/manim#2918]
```python
    ...
    def interpolate_color(self, mobject1, mobject2, alpha):
        """Interpolates an array of pixel color values into another array of
        equal size.

        Parameters
        ----------
        mobject1 : ImageMobject
            The ImageMobject to transform from.

        mobject1 : ImageMobject

            The ImageMobject to transform into.
        alpha : float
            Used to track the lerp relationship. Not opacity related
       """
```
In the documentation, in the parameters section as you can see the second parameter is supposed to be `mobject2` and not `mobject1`.

Also, don't you think it's a bit misleading to say that this `"Interpolates an array of pixel color values into another array of equal size"` when it seems to interpolate an `ImageMobject` into another?

I just started working with this a few minutes ago so I could be missing something here, just wanted to report this before I moved on from it!

**Comment by OmegaTwiddle** [comment]
I believe the documentation error has been fixed with [the above PR](https://github.com/ManimCommunity/manim/pull/2919).

Can this issue be closed out?

Note, I saw the old docstring in ./i18n/gettext/reference/manim.mobject.types.image_mobject.ImageMobject.pot -- I tried to regenerate these docs, but wasn't able to figure out how to regen that msgid...

**Comment by behackl** [comment]
Indeed, it can -- thanks for having a look at this!

Regenerating our translation strings is a separate issue, we'll need to look into that.
