### ISSUE TITLE
Tex object rendering bug

### ISSUE THREAD

**Issue by 7lang2yan** [ManimCommunity/manim#2955]
## MathTex rendering pmatrix may possibly result in missing right brace ')'

```py
P3d = MathTex(
            'P &= ', # 0
            r'\begin{pmatrix} 1 & 2 & 0 \\ 1 & 3 & 1 \\ 0 & 1 & 5 \end{pmatrix}', # 1
            r'\left(', # 2
            r'\begin{pmatrix} 1 & 1 & 0 \\ 2 & 3 & 1 \\ 0 & 1 & 5 \end{pmatrix}', # 3
            r'\begin{pmatrix} 1 & 2 & 0 \\ 1 & 3 & 1 \\ 0 & 1 & 5 \end{pmatrix}', # 4
            r'\right)^{-1}', # 5
            r'\begin{pmatrix} 1 & 1 & 0 \\ 2 & 3 & 1 \\ 0 & 1 & 5 \end{pmatrix} \\', # 6
            r'&= \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix} \\' # 7
        )
        self.play(
            Write(P3d[0:7])
        )
        self.wait(0.5)
        self.play(
            Write(P3d[7])
        )
```

## Additional media files

https://user-images.githubusercontent.com/94862670/191455133-419ae152-151c-4f69-b31f-e034fd67437d.mp4

**Comment by aRySt0cat** [comment]
It seems to be caused by replacing **\left** and **\right** with **\big** in `_modify_special_strings` of SingeStringMathTex when they are imbalanced.
This changes the number of Submobjects when a SingleStringMathTex is created using all TeX strings and when a SingleStringMathTex is created using each element, so the `_break_up_by_substrings` does not work correctly.
The number of Submobjects of **\left(**, **\right)** changes according to the height of their contents, so it is difficult to identify where the difference in the number of Submobjects comes from.

For now, the only solution seems to be to change the number of lefts and rights in each element to make them balanced as below and count the number of the Submobjects by yourself if you want to animate with them.

```python
P3d = MathTex(
            'P &= ', # 0
            r'\begin{pmatrix} 1 & 2 & 0 \\ 1 & 3 & 1 \\ 0 & 1 & 5 \end{pmatrix}', # 1
            r'''\left(
            \begin{pmatrix} 1 & 1 & 0 \\ 2 & 3 & 1 \\ 0 & 1 & 5 \end{pmatrix}
            \begin{pmatrix} 1 & 2 & 0 \\ 1 & 3 & 1 \\ 0 & 1 & 5 \end{pmatrix}
            \right)^{-1}''', # 2
            r'\begin{pmatrix} 1 & 1 & 0 \\ 2 & 3 & 1 \\ 0 & 1 & 5 \end{pmatrix} \\', #3
            r'&= \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix} \\' # 4
        )
self.play(
    Write(P3d[0:4])
)
self.wait(0.5)
self.play(
    Write(P3d[4])
)
```

**Comment by 7lang2yan** [comment]
Thanks！
