### ISSUE TITLE
Documentation Website Has Broken Links: I Can't Submit Pull Requests!

### ISSUE THREAD

**Issue by AnonymoZ** [ManimCommunity/manim#2960]
On each page of Docs.Manim.Community there is a Pencil icon if editing needs be for that page.
But now if I click the Pencil for any page it gives a 404!

For example:
If I go on this link:
https://docs.manim.community/en/stable/reference/manim.mobject.geometry.arc.Circle.html

And click the Pencil on the top-right I get a 404!

Fix it!

**Comment by behackl** [comment]
Thanks for letting us know, I wasn't aware our documentation theme has added an edit button feature.

The problem is: the way this is [currently implemented]( https://github.com/pradyunsg/furo/blob/main/src/furo/theme/furo/components/edit-this-page.html) does not work correctly with documentation pages generated from docstrings via `autodoc`: In the example you gave above, https://docs.manim.community/en/stable/reference/manim.mobject.geometry.arc.Circle.html tries to link to (after setting up things correctly) https://github.com/ManimCommunity/manim/edit/main/docs/source/reference/manim.mobject.geometry.arc.Circle.rst, so it basically is looking for the corresponding document in our `docs/source` directory.

However, it cannot be found there as this page is autogenerated from the docstring of the `Circle` class in https://github.com/ManimCommunity/manim/blob/44f78f1dfdd7498542869fc06bb39619f2b2d57b/manim/mobject/geometry/arc.py#L467-L490

We'll have to disable the feature for now.

**Comment by AnonymoZ** [comment]
Huh? But what do we do if we have edits to make?

Many pages have _properties_ left unexplained/blank.
Important properties not even mentioned in the Doc pages.

Text(...) has attributes not explained in the Doc.
Also, Circle(...) lacks the important attribute _stroke_width_ which works, is a crucial parametre but never mentioned it is possible to customise.

**Comment by behackl** [comment]
> Huh? But what do we do if we have edits to make?
> 

You can still edit the documentation of classes and methods, you just need to navigate to the corresponding page manually on GitHub. The redirect from the documentation page to GitHub does not work; editing the docstrings works just normally.

> Text(...) has attributes not explained in the Doc. Also, Circle(...) lacks the important attribute _stroke_width_ which works, is a crucial parametre but never mentioned it is possible to customise.

`stroke_width` should be documented as an argument of `VMobject` in https://docs.manim.community/en/stable/reference/manim.mobject.types.vectorized_mobject.VMobject.html#manim.mobject.types.vectorized_mobject.VMobject. With how the documentation is setup currently, you often have to look for arguments in the base classes of the class you are interested in. (Not saying I particularly like this system, but that is how it currently is.)

**Comment by AnonymoZ** [comment]
O.K.
