### ISSUE TITLE
Passing a label_constructor function to NumberLine.add_labels() does not set the label properties.

### ISSUE THREAD

**Issue by vahndi** [ManimCommunity/manim#2989]
## Description of bug / unexpected behavior

Passing a `label_constructor` function to `NumberLine.add_labels()` does not set the label properties. The bug appears to be in lines 565-567 of `manim\mobject\graphing\number_line.py`, which reads:

    label_constructor = (
            self.label_constructor if label_constructor is None else label_constructor
    )

Changing this to:

    self.label_constructor = (
            self.label_constructor if label_constructor is None else label_constructor
    )

fixes the problem.

## Expected behavior
Label properties should be set using the label_constructor function

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
from manim import Scene, Axes, Text


def make_tick_label(text: str) -> Text:
    return Text(text, font='Arial')

numbers_to_bar_names = {
    i: f'a{i}b' for i in range(11)
}


class BugDemo(Scene):

    def construct(self):

        axes = Axes(
            x_range=[0, 10],
            y_range=[0, 10],
            y_axis_config={
                'include_numbers': True,
                'font_size': 24,
                'label_constructor': make_tick_label
            }
        )
        axes.x_axis.add_labels(
            numbers_to_bar_names,
            font_size=24,
            label_constructor=make_tick_label
        )
        self.add(axes)
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

**Existing Code**
![image](https://user-images.githubusercontent.com/8841674/195459159-def6993d-0077-4bd1-90b7-e26778bc8416.png)

**New Code**
![image](https://user-images.githubusercontent.com/8841674/195459181-18194cd0-2aaa-4203-949f-fb3850797c60.png)

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by denieryd** [comment]
Why did you create issue instead of pull request ?

**Comment by vahndi** [comment]
I didn't know about whether you have unit testing requirements etc for pull requests. I can make one later in the week when I have a bit more time.

**Comment by MrDiver** [comment]
Just a quick tip on the side, if you want to reference code in your issues or pull requests you can view it in github and on the side you can shift + mouse click on the numberline to select some lines, then you can click on the 3 dots and copy permalink, or if you want to start your issue with that you can actually create your issue from there

![grafik](https://user-images.githubusercontent.com/17803932/200515781-8133913d-d5d7-4e04-b3ce-491d5f5e72b9.png)

This gives you a nice code snippet which the devs can click on in order to see the surrounding code as well!

https://github.com/ManimCommunity/manim/blob/d76fa670cad3f74953666fa1860be32bc896f738/manim/mobject/graphing/number_line.py#L565-L567

Hope that helps 🥳 Thanks for contributing!

**Comment by MrDiver** [comment]
I would actually argue that we have a little bit of thinking to do on that issue ? Because i think it is a little bit confusing behavior if the `add_labels` method changes the state of `NumberLine` which is then used in `_create_label_tex`. And it also doesn't allow for differently created labels if i think about it correctly (not that there is a use case for that i suppose but still who doesn't want rainbow colored labels 🌈 ).

Any way, i would probably suggest also adding a parameter to the `_create_label_tex` function to accept a label constructor. (Don't start implementing it right away xD let's first discuss this)

**Comment by vahndi** [comment]
Thanks for the tips!
I think I see what you're saying. Looking at the way a local `label_constructor` is handled in `NumberLine.add_numbers` and `Numberline.get_number_mobject`, it looks like the intention may have been to assign the passed value to the local `label_constructor` and use that later in the call to `_create_label_tex`, but this is not done.
Also, `label_constructor` is explicitly listed in the params for `_create_label_tex` so it seems like making it optional and then using it if it's passed, with a fallback to `self.label_constructor` would work here?
Forgive my ignorance, but what's the config dictionary?

**Comment by vahndi** [comment]
Ok cool, shall I rework the code to be consistent with the other methods and create another pull request?

**Comment by behackl** [comment]
> Ok cool, shall I rework the code to be consistent with the other methods and create another pull request?

Yes, please. This seems like a better, more consistent solution than storing the label constructor in an attribute. (Storing all sorts of passed keyword arguments is one of the design choices in Manim that I personally dislike the most.)
