### ISSUE TITLE
[Docs] Quickstart - Transform vs ReplacementTransform

### ISSUE THREAD

**Issue by DegrangeM** [ManimCommunity/manim#3139]
In the quickstart tutorial https://docs.manim.community/en/stable/tutorials/quickstart.html

The `transform` method is introduced : https://docs.manim.community/en/stable/tutorials/quickstart.html#transforming-a-square-into-a-circle

A little after, in `Using .animate syntax to animate methods`, the `ReplacementTransform` method is used.

It is confusing for new learner because they don't know why this new function is used instead of the other.

The docs should either : 

- Only use the `transform` method (if possible)
- Only use the `ReplacementTransform` method (if possible)
- Keep using `transform` and `ReplacementTransform` but explain the new method

**Comment by bdotsamir** [comment]
![image](https://github.com/ManimCommunity/manim/assets/26691026/f2a76c9c-d7e4-450a-b393-5f1ba1b1fd31)

This should be explained somewhere in the quickstart! This was a massive pain-point for me when I was learning Manim for the first time- I saw Transform used in 3b1b's videos and so that's what I used, but I was wondering why the design decision was to replace the original mobject with a reference to the transformed mobject. Caused headaches when I was trying to remember which variables held which Mobjects. ReplacementTransform solved this prayer.
