### ISSUE TITLE
Perception on pull requests

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#319]
Reviewing #311, I realize that I have a different perception of pull requests then e.g. @leotrs.

Like in the updated contribution guideline #311 a pull request could look like this:
 
1. Running locally all `pytest` from the main `manim/` folder
2. Including `black` autoformation
3. update the docstrings
4. strongly preferred that you include tests that accompany them in your PR
5. your proposed changes are as general as  possible

As a new contributor, I would feel very intimidated by this.

And also as a developer, I find this workflow a bit too much for a first presentation of an idea.
One person once said to me: 
"It's better to have a good idea that is poorly presented, 
then to have a poor idea that is well presented."
With this in mind, I want to say, that the upper workflow would be in theory very good, but in practice not so easy to handle.

I suggest, that the first presentation of an idea, so the first commit to a new pull request should be as easy as possible, even if that means that the pull request is not complete. 
That means no docstrings, not as general as possible (making things as general as possible can take a lot of time!), and no tests you have to include. To clarify: It is appreciated if you do so, but it is should not be mandatory. 

Then, after the first look from other devs, which find this idea good, one can start to add docstrings, generalize the code, maybe add tests, etc.

Additional to this: 

When working on new things, I work with some minimal examples, that won't be useful for the final repo, but are very useful for trying this new feature.
Should these examples be added to a pull request?
My idea would be: Yes because then other devs have the chance to test this feature easily.
Before merging, these examples could be removed again.

**Comment by huguesdevimeux** [comment]
I COMPLETELY agree with 

> And also as a developer, I find this workflow a bit too much for a first presentation of an idea.

But, still, tests and docs _are_ and should be mandatory. That's what will keep manim still safe for contributing.

> I suggest, that the first presentation of an idea, so the first commit to a new pull request should be as easy as possible, even if that means that the pull request is not complete.

So yes, for a presentation of an idea, this is absolutely super. I'm sure we will have a lot more contributions than we would if we restrict that much PR from the beginning.

But I'm not very experienced with open source stuff and even less a `professional` dev.

**Comment by leotrs** [comment]
Hi @kolibril13, thank you for sharing your thoughts on this issue. We certainly want to be as welcoming as possible. 

> 1. Running locally all `pytest` from the main `manim/` folder
> 2. Including `black` autoformation
> 3. update the docstrings
> 4. strongly preferred that you include tests that accompany them in your PR
> 5. your proposed changes are as general as possible

All of these are standard requirements to contribute to big open source projects. Emphasis on "big" here. Manim is currently used by dozens (hundreds?) of people, and in the future I would love to reach thousands, if not tens of thousands more. As developers, we are responsible to not include in the library something that may interfere with the user experience, workflow, and productivity. For example, Microsoft cannot ship PowerPoint with bugs or without testing, NumPy cannot accept computational errors, and matplotlib cannot ship functions that render incorrectly. All of these must be well formatted, documented, and tested. In our case, we are responsible for not shipping code that may interfere with an educator's deadlines when producing class materials using manim. Perhaps we are not quite there yet, but if we ever want to see manim used by more and more people, we must strive to ship stable software.

> As a new contributor, I would feel very intimidated by this.

I understand where you're coming from, but unfortunately there is a trade-off to be made here, and I personally fall on the side of caution. We cannot ship software that breaks users' experience.

> And also as a developer, I find this workflow a bit too much for a first presentation of an idea.

A PR is not meant to be the first presentation of an idea. A PR is a "Pull Request", which means "my idea is ready, implemented, tested, and stable, and is ready to be reviewed by the rest of the developers". For the first presentation of an idea, or a feature request, you should open an issue.

> One person once said to me:
> "It's better to have a good idea that is poorly presented,
> then to have a poor idea that is well presented."

This is a very interesting philosophy. Like I said above, the way to present an idea is through issues (or discord, chat, email, etc). PRs have a functional role that is far beyond "presenting" an idea.

> I suggest, that the first presentation of an idea, so the first commit to a new pull request should be as easy as possible, even if that means that the pull request is not complete.

As said above, a great way of introducing an idea to the dev team is through an issue. See for example what I did recently in #293. 

> That means no docstrings, not as general as possible (making things as general as possible can take a lot of time!), and no tests you have to include. To clarify: It is appreciated if you do so, but it is should not be mandatory.

Unfortunately, without documentation, it will be hard for the dev team to know what's going on in a new PR. One thing you have to be mindful of is that everyone here is a volunteer, and asking a volunteer to spend more time than they are willing or able is generally considered inconsiderate and even rude. You can think of a PR as turning in your homework. If you present a badly formatted, illegible, unorganized document, in the best case scenario, you are asking your teacher to spend way more time than necessary to grade it. In the worst case scenario, you will get a failing grade.

> Then, after the first look from other devs, which find this idea good, one can start to add docstrings, generalize the code, maybe add tests, etc.

This can already be done by marking a PR as a draft. You are right in that a PR doesn't need to be 100% perfect to be submitted or reviewed, and it can be under ongoing development as well. But in order to be merged, it should be documented/tested/general (at least somewhat).

> When working on new things, I work with some minimal examples, that won't be useful for the final repo, but are very useful for trying this new feature.
> Should these examples be added to a pull request?
> My idea would be: Yes because then other devs have the chance to test this feature easily.
> Before merging, these examples could be removed again.

You can add/remove anything you want while the PR is under development or marked as a draft. But make sure to add a big warning saying "this file is not mean to be merged". (I would much rather that they don't be committed because they will remain in the git history, but hey as long as they aren't merged that's fine too I guess.) Remember, when you deem a PR to be "ready for merging", it must be ready to be used by dozens/hundreds/thousands of other people. We do not want to ship unnecessary/unstable/illegible stuff. 

NOTE: I'm grasping for words here, but don't take me **too** seriously here. I do not think that each PR must be totally perfect, and I do not think that devs are necessarily like teachers to contributors and PRs are homework -- we're all learning together here. What I mean to say in general is that well-crafted PRs are, in a way, a show of respect and care for the community, and also a way to simplify the devs' lives by a ton. If you have an idea that is not 100% tested/documented/implemented, that's what issues and discord and draft PRs are for, and I think we can say we are doing a great job at welcoming these type of contributions as well.

Final word: use your best judgment when contributing, and keep in mind that with each issue/PR/conversation you are asking a volunteer to spend some of _their time_ on _your idea_. As a quick example, I've already spent 30min today dealing with open issues, and that's time that I don't spend writing my dissertation. If you find a dev with time to spare, then that's awesome. If not, then the responsibility is on you to convince the dev team to merge your changes, and the dev team should be allowed to reserve merging rights to PRs that are legible/tested/documented/general/stable/etc.

**Comment by leotrs** [comment]
After reading my own text again, I think the current language I'm proposing in contributing.md might be a bit inflexible. We can perhaps add some language to reflect the fact that PRs don't have to be 100% perfect, but the more complete they are, the easier it will be for devs to review and the faster they will get merged. I do stand by everything I said in this thread tho.

**Comment by kolibril13** [comment]
@leotrs thank you a lot for taking your time and writing such an in-depth view on pull requests.
This is my first bigger Open-Source project and had the idea that pull request are more like a playground where you can tinker together on half-finished ideas so that they might maybe become a part of the main branch in the end.
I was not aware that they are meant to be tested/documented/implemented properly from the beginning, and want to apologize that this was not the case in some of my previous pull requests. Discussing half prepared ideas in issues instead sounds good.



> Manim is currently used by dozens (hundreds?) of people, and in the future, I would love to reach thousands, if not tens of thousands more

This is a really inspiring and visionary thought. I see that with this vision it makes a lot of sense to pay attention to maintain the code properly. 

To the preparation of code:
Maybe we could make a script that helps to prepare the repo for making a pull request without too many manual steps, something like
```
import os
from pathlib import Path

path = Path.cwd().parent

os.system(f"black {path}")
os.system("pytest")
```

**Comment by leotrs** [comment]
> This is my first bigger Open-Source project and had the idea that pull request are more like a playground where you can tinker together on half-finished ideas so that they might maybe become a part of the main branch in the end. I was not aware that they are meant to be tested/documented/implemented properly from the beginning, and want to apologize that this was not the case in some of my previous pull requests. Discussing half prepared ideas in issues instead sounds good.

To be completely fair, what I am advocating for is for us to steer into a "big FOSS project model". Up to now, we haven't been following the instructions I laid out to a tee. So there's no need to apologize at all! Like I said, you can PR whatever you want, but its state will determine how long it will take for it to be ultimately merged.

Also, on the topic of tinkering: your own fork and other (non-master) branches are exactly suitable for this purpose. The main repo's master branch should be kept for code that is ready to be shipped to all users. (Again, I'm advocating that we start doing this, I'm not saying that this is how it's always been.)


> Maybe we could make a script that helps to prepare the repo for making a pull request without too many manual steps

If you think this is a feature that will be appreciated by most users, feel free to start an issue or PR ;) I personally think this is unnecessary since there are only two manual steps (black and testing) that this script would be replacing. So instead of executing two things, you have to execute one thing. Not much of a difference. But I don't make unilateral decisions, so please feel free to open an issue to hear what the rest of the team thinks.
