### ISSUE TITLE
Generated surface has artifacts

### ISSUE THREAD

**Issue by MartensCedric** [ManimCommunity/manim#3268]
### Describe the bug
When i generate a surface, I observe strange artitifacts

**Code**:
```py
from perlin_noise import PerlinNoise
def perlin_noise(noise, u, v, octaves=8):
    total = 0
    p = [u, v]
    for i in range(octaves):
        total += (1 / (2 ** i)) * noise([(2 ** i) * x for x in p])
    return total / (2 - 1 / (2 ** (octaves - 1)))


class TerrainGen(ThreeDScene):
    def construct(self):
        axes = ThreeDAxes()
        noise = PerlinNoise()
        res = 64
        surface = Surface(
            lambda u, v: axes.c2p(u, v, perlin_noise(noise, u, v)),
            u_range=[-1, 1],
            v_range=[-1, 1],
            resolution=(int(np.sqrt(res)), int(np.sqrt(res)))
        )
        surface.set_style(fill_opacity=1)
        surface.set_fill_by_value(axes=axes, colorscale=[(RED, -0.5), (YELLOW, 0), (GREEN, 0.5)], axis=2)
        surface.scale(5, about_point=ORIGIN)
        three_d_stuff = VGroup(surface)
        self.set_camera_orientation(theta=70 * DEGREES, phi=75 * DEGREES)
        self.begin_ambient_camera_rotation(rate=PI / 20)
        # self.add(axes)
        self.play(Create(surface))
        self.wait(5)
```

**Wrong display or Error traceback**:

### Additional context
![image](https://github.com/3b1b/manim/assets/18620025/6ad8d946-276c-4e63-a94b-feb00101d4d6)

**Comment by uwezi** [comment]
Those are caused by the Bézier smoothing of the surface. Your function appears to make small but abrupt changes in the vicinity of the sampling points which then triggers this behavior. It gets better when you use a higher resolution or by making sure that your surface function doesn't have a higher dynamic than the sample points (low pass filtering).
The artifacts also disappear when you disable the surface smoothing with `should_make_jagged=True` when Manim uses straight elements instead of Bézier curves.
