### ISSUE TITLE
Feature request: optionally suppress "Manim Comunity v{version}"

### ISSUE THREAD

**Issue by jeertmans** [ManimCommunity/manim#3326]
## Description of proposed feature

Hello! As of recent versions of Manim, it is not possible to suppress the `Manim Community v{version}` message that is printed out when importing `manim`.

Actually, this is because importing `manim` imports `manim.__init__`, which in turn imports `manim.__main__` with this: https://github.com/ManimCommunity/manim/blob/88836df8ab1ea153ed57848a74a694c517962163/manim/__init__.py#L104-L113

Before, I could suppress the message using some redirect, but now if fails

```python
>>> import os
>>> from contextlib import redirect_stdout
>>> 
>>> with redirect_stdout(open(os.devnull, "w")):
>>>     print("HELLO")
>>>     import manim
Manim Community v0.17.2
```
because Rich will still print to `stdout` (since the console was created before `stdout` was redirected). 

Rich's console has an optional `file` argument, but there currently seem to be a bug with it, reported in https://github.com/Textualize/rich/issues/3083, that makes Rich's consoles only print to stdout.

A **nice feature** would be to make the behavior optional.

## How can the new feature be used?

There are a few possible solutions:

- Not printing the version at all;
- Moving the print message inside the `__main__`:
https://github.com/ManimCommunity/manim/blob/88836df8ab1ea153ed57848a74a694c517962163/manim/__main__.py#L59-L60
- Optionally print (or disable print) with some environ variable
- ...

## Additional comments

I develop Manim Slides, a Manim plugin, and I'd like to avoid printing the Manim Community version every time I import this package, because the user does not really need to know that.

**Comment by MrDiver** [comment]
You can just make a PR for that if you want, i would still say it is useful for your users to know the version, because as soon as they have problems with the Plugin you will want to know the version number.

**Comment by uwezi** [comment]
With the current version 0.17.3 I don't observe the problem you describe here - the redirection suppresses the message. Was this perhaps a flaw in 0.17.2?

![bild](https://github.com/ManimCommunity/manim/assets/8582807/7731a01e-57bf-45a7-a318-89fe4ff68d66)

**Comment by behackl** [comment]
Thank you for the suggestion! The version banner is (unfortunately) rather helpful for the helpers in our forum because it is a quick way to tell whether people are invoking manim vs. manimlib, so I think we'll want to preserve the current default behavior -- and as a consequence of this, the priority for working on this is rather low. Contributions are welcome. :-)

Regarding your suggestions:

- Not printing the version is not ideal (as others have already mentioned too),
- I am not sure whether the `__main__` logic in that file really does anything: the `main` function defined above doesn't do anything, and the `__name__` seems to be set to `manim.__main__` whenever manim is not invoked via the module directly (i.e., via `python -m manim`).
- It's certainly possible to introduce a `--hide-splash` or something along these lines to suppress the version.

Thanks for your work on Manim slides!

**Comment by jeertmans** [comment]
@behackl and @MrDiver I totally agree with that printing the version has nice pros.

But imo the version printing could be limited to the CLI command (and not the module itself).

I will do a PR when I have some time :)

**Comment by jeertmans** [comment]
@uwezi i dis not check when the console printing was changed, but the version is only printed if you have IPython installed if I understand correctly.

**Comment by uwezi** [comment]
when I remove the redirection from your example and run the script the version is printed to the console even without using IPython - so for me your hack works...

**Comment by jeertmans** [comment]
Ok that's weird because I tested that like several times before making this issue.. Anyway I opened an issue on Rich's repo about that.

On the other side, I opened a PR to allow hiding the splash :-)
