### ISSUE TITLE
what about adding blending modes?

### ISSUE THREAD

**Issue by ubaldot** [ManimCommunity/manim#3469]
## Description of proposed feature
Given that you touched colours, I have a provoking thought: what about adding blending modes in the future? 

At first glance the VMObject class shall be modified such that it takes an  additional parameter "blending_mode=" that can take values in an enum {normal (default), add, multiply, screen, ...}. 

Blending modes explained: https://www.youtube.com/watch?v=EOoMakEVh_s

**Comment by ubaldot** [comment]
I think that Manim order and layers can be placed in a 1-1 correspondence, if the set of mobject used internally in Manim keeps the property of “totally ordered” set. 
For example, in the submobjects attribute of Scene the elements are ordered from the bottom to the top, and there I can see layers of course. If the internal machinery of manim does something special that mix up things I dunno of course, I am a user, not a developer. :) 

A use case? Well, literally *every* program that deals with computer graphics have blending modes. 
The same applies for functions like “bring to front”, “send to back”, etc., related on how mobjects are rendered on the screen. :)
I do that manually now, but note that today these are considered standard features. :)

**Comment by MrDiver** [comment]
I would note back that Manim is not really a "graphics" program in that sense because it is not meant for editing images and so on. And we can also have 3D animations in the future which will probably interfere a lot with the idea of blending modes.

So i agree most of the applications that deal with editing images has blending modes, but Manim is a 2D/3D Animation program which does not really go into that use case.
Also with the bring to front and send to back function it would not really make sense in a 3D context. Only 2D and very limited space of animations

Hope that explains the context a little and why i asked about a specific usecase.

**Comment by ubaldot** [comment]
Nope. Manin is indeed a `graphics` program. 
Nope. Generalizing "adding blending modes" to "editing images and so on" as you did is allegedly a mystification. Nobody claimed that Manim is a tool for "editing images". 

> Only 2D and very limited space of animations.

False. Send to Beck/Bring to front don't represent a **_limited_** space of usage in 2D context. They are **_widely_** used in 2D context.
