### ISSUE TITLE
ManimColor: Adding documentation and examples for creating colors

### ISSUE THREAD

**Issue by ubaldot** [ManimCommunity/manim#3472]
Time to work with colours! :D

```
BG_rgb = (40, 85, 120)
hsv = ManimColor().from_rgb(color).to_hsv()
```

will return `TypeError: ManimColor.__init__() missing 1 required positional argument: 'value'`, whereas the docs say

``` 
class ManimColor(value, alpha=1.0)
 
...
 PARAMETERS:
-  value (ParsableManimColor | None) – Some representation of a color (e.g., a string or a suitable tuple).
```

Is that `None` a "docs' bug"?

**Questions:**
1. How shall I create a hsv ManimColor from a rgb/hsv tuple?
2. Once I have some sort of `hsv = ManimColor(... `, wouldn't be nicer to access attributes e.g. with `hsv.hue, hsv.saturation‚ hsv.value` rather than using the `.to_hsv()`method?  
3. I noticed that the `hsl` color space has been removed, is there any special reason?
4. Would you mind to add some examples in the docs so the users could better understand how to create their colours? 
 
Keep up the good work !

**Comment by MrDiver** [comment]
And to answer your original question
```py
>>> hsv = ManimColor.from_rgb(None).to_hsv()
>>> hsv
(0.0, 0.0, 0.0)
>>> hsv = ManimColor(None)
>>> hsv
ManimColor('#000000') 
```
None doesn't mean Nothing

**Comment by ubaldot** [comment]
I would do the following way:

1. Add a Warning that differently from he wide majority of users' Manim classes, objects are instantiated through classmethods, for example, with:

>>> hsv = ManimColor.from_rgb(0.3, 0.4, 0.8).to_hsv()

and therefore, calls like hsv = ManimColor(xyz) won't work. 

2. Remove all things that distract the user, such as

> This is done in order to reduce the amount of color inconsitencies by constantly casting between integers and floats which introduces errors.

3. Avoid reporting internal methods in the user docs (those who start with _)

4. Proof read the docs from possibly some users (not developers). 

5. Clean up the overall page (for example classmethod parse is reported twice).

**Comment by behackl** [comment]
> 1. Add a Warning that differently from he wide majority of users' Manim classes, objects are instantiated through classmethods [...] and therefore, calls like `hsv = ManimColor(xyz)` won't work.

This is not the case. The class methods (which examples could be added to) are an additional interface for creating instances. Based on RGB values, you can still create an object in the conventional way via `ManimColor((R, G, B))`. You do not need to use the static `from_rgb` method.

> 2. Remove all things that distract the user, but are useful for developers, such as [...]

I am not sure I agree with the complete removal; there is information relevant for devs that needs to be put somewhere too; docstrings are not purely user-facing features. 

> 3. Avoid reporting internal methods in the user docs (those who start with _)

I agree, that is not difficult to change. We should investigate whether there was a particular reason why this was enabled.

 > 4. Proof read the docs from possibly some users (not developers).

Contributions and improvements to the documentation are welcome!

> 5. Clean up the overall page (for example classmethod parse is reported twice).

The signature is listed twice because there are two different return types, Sphinx generates it like that. Not sure we have much more control about how exactly this is displayed.

**Comment by MrDiver** [comment]
So i would now word it a bit different because saying something like it has no utility for the user is really trashing the whole picture why this change was made in the first place.

Yes it has utility for the user even if you do not see it directly, render times are reduced, many errors have been solved, color shifting due to the constant conversions has been completely removed as a problem.

So please do not go around and say something like it has no utility for the user if you're seeing a tiny part of it.

Next point is, yes it is kind of an expectation that you read the documentation and if you do not understand something then you're able to look up why it may not work or ask on discord. Because personally i think the documentation is pretty clear on which functions are class functions and which are not.

And if you say things like time to write down a mission please join us in the discord and become a dev and actually look at what is done behind the scenes, because there are clear goals for the library

And lastly i would also suggest to you that you first think about multiple stand points for which things might be used because just having one perspective really shifts the reality of the situation, so keep answers short and useful and provide use cases and information that is relevant to the dev process instead of using exaggerations in every sentence.

Thanks for your suggestion
