### ISSUE TITLE
The brightness of the video changes when the program moves on to the next "play(animations)"

### ISSUE THREAD

**Issue by alukang** [ManimCommunity/manim#3490]
# If the background is "NumberPlane", the flickering  will be noticeable
 ![test](https://github.com/ManimCommunity/manim/assets/25880096/bcceadd7-dac0-4b5d-8920-0c2590ba6e0d)
from manim import *
class test01(Scene):
    def construct(self):
        ax = NumberPlane()
        cirs = []
        for i in range(-5,6,2):
            for j in range(-5,6,2):
                cirs.append(Circle(arc_center = ax.coords_to_point(i,j),radius=1))
        self.add(ax)
        [self.play( Create(cir)) for cir in cirs]

**Comment by uwezi** [comment]
I have never seen anything like this before... I'll have to have a look at your code...

**Comment by uwezi** [comment]
What are your render settings? 
Which version of Python, ffmpeg, Manim etc are you using?
(essentially all the questions which you chose to not answer from the template)

Because on my system I cannot reproduce this behavior...

https://github.com/ManimCommunity/manim/assets/8582807/b7536989-0fed-419b-9d90-8f7224a0146a

**Comment by alukang** [comment]
The problem was found, it was a problem with my player(Potplayer), and when I used another one(VLC madia player), the video was normal.
