### ISSUE TITLE
[Community Devs] Please, let's use github features

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#351]
So i was just chilling on github (yes) and (re)discovered some of the amazing feature GitHub provides, which, I think, we don't use enough. 
So I _really_ think it would make everything easier if we were using these. 

So, lets try to  : 
- Use the assignees things : Let's assign someone/ourself as soon as we can. It would make the issue board cleaner. 
- Use the Projects tab WAY more for pretty everything. Very powerful tool there. So everytime there is a new big feature implemented, please create a project, so everyone (including yourself) will be able to see its progress. I think, for example, we should USE more the Migration To Dataclass Project, as well as creating one for the current big features under development (eg, CONFIG). 
- Create a big project to sort all the issues in one place. The idea would be to do something like that : https://github.com/Shabang-Systems/Condution/projects/2
- **REALLY** distinct the use of draft PR and non-draft PR. In theory, draft PR are in progress, and PR undrafted **must** be compltetly done and therefore don't get any new adding (except change requests during reviews)
- Dunno. Ideas ? 

Share your thoughts  !

**Comment by leotrs** [comment]
Thank you for bringing this up. Super 100% agree here. Using these tools is going to reduce the time we otherwise spend doing reviews and figuring things out.

On the issue of assigning devs to issues/PRs: different teams handle this in different ways. For example, a popular way of doing it is that if you open a PR, then you _must_ request a review from someone. If that person cannot do it, they _must_ request someone else instead and take their name off the list. We can do the same with assignees. There are also bots that will choose who is the best person to assign, or bots that will assign someone at random so that the load is balanced.

There's also [this](https://github.com/orgs/ManimCommunity/teams/core). If we were using this board more, I think this issue could have been posted there instead ;)

**Comment by huguesdevimeux** [comment]
> On the issue of assigning devs to issues/PRs: different teams handle this in different ways. For example, a popular way of doing it is that if you open a PR, then you _must_ request a review from someone. If that person cannot do it, they _must_ request someone else instead and take their name off the list. We can do the same with assignees. There are also bots that will choose who is the best person to assign, or bots that will assign someone at random so that the load is balanced.

Very good. WOuld be a cool thing IMO.

> There's also [this](https://github.com/orgs/ManimCommunity/teams/core). If we were using this board more, I think this issue could have been posted there instead ;)

oooooh totally!

**Comment by huguesdevimeux** [comment]
Closing this in favour of the core discussion.
