### ISSUE TITLE
latex error converting to dvi.

### ISSUE THREAD

**Issue by euoguga** [ManimCommunity/manim#3511]
Hi, guys!

When I try to colorize my latex equation, the fowlling happens:

latex error converting to dvi. See log output above or the log file: media/Tex/1b397957b87f17df.log

what's going on?

thank you!

**Comment by MrDiver** [comment]
Can you please provide more information for your Problem, and look at the template that is provided for how to create an issue.

Because the only information you gave is that you tried to render an illegal latex snippet.

I will close this for now until more information is provided, or try asking on the discord server in the help channel.
