### ISSUE TITLE
Option to scale stroke_width

### ISSUE THREAD

**Issue by hyranno** [ManimCommunity/manim#3525]
## Description of proposed feature
Add option to mobject.scale to scale including vmobject.stroke_width.
mobject.scale just changes its points,  does not touch stroke_width for now.
But sometime I want to scale them including stroke_width, to preserve the appearance.

## How can the new feature be used?
`mobject.scale(scale_factor, scale_stroke_width=True)`

## Additional comments
I expect code like below, but no sure while I'm new to python and manim.
```
def family_members_with_stroke_width(self) -> list[Self]:
    return [m for m in self.get_family() if  m.get_stroke_width && m.get_stroke_width() > 0]
```
```
def scale(self, scale_factor: float, scale_stroke_width=False, **kwargs) -> Self:
    if scale_stroke_width :
        for mob in self.family_members_with_stroke_width():
            mob.set_stroke(width=scale_factor * mob.get_stroke_width())
            mob.set_stroke(width=scale_factor * mob.get_stroke_width(background=True), background=True)
    self.apply_points_function_about_point(
        lambda points: scale_factor * points, **kwargs
    )
    return self
```

**Comment by SORVER** [comment]
Can you explain more or show a video?

**Comment by hyranno** [comment]
![image](https://github.com/ManimCommunity/manim/assets/6697334/09c25536-98e8-4265-a7a6-ae1c5f8cf333)
Think scaling the circle at the center.
`mobject.scale(4)` results the right, breaking the propotion of stroke to fill.
To result the left which preserve the propotion, its `stroke_width` should be scaled too.

**Comment by Boris-Filin** [comment]
Hello there!
I have tested an implementation of your idea, I think I got it to work.
In short, the set_stroke is only called once instead of iterating over the family members, because the function itself is recursive.
There are some other modifications, like calculating the absolute value of the resulting stroke, because otherwise negative scaling removes the outline entirely.

Here is how the result looks:
![Screenshot 2024-10-18 205521](https://github.com/user-attachments/assets/f594ddaf-a89f-47b9-a52e-a11c26b0fe63)

Both text objects have an outline of 3px, and all circles were instantiated with outline of 100px, but the middle one is scaled to 25%.

Could you please assign me the issue when you have a moment?
We need the OSs contribution for university -_-
