### ISSUE TITLE
Add a way to tests logs

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#354]
Currently, logs are tested by comparing with `==` two strings (generated logs and expected logs), which makes it quite hard to debug. 

It think we should implement a thing to parse the logs, so when performing a comparison one would be able to precisely knwo what differ (i:e which line, etc) between two logs. 

Or maybe we should save logs to a JSON/CSV file, to make it even easier. 

Thoughts ?

**Comment by leotrs** [comment]
Ooof parsing logs is a Whole Thing.

My suggestion for now would be to compare certain properties of the log files instead of just comparing the strings. I would start by comparing the number of lines and the text _without whitespace_.

Other than that, if a comparison with `==` fails, we can output a prettier diff rather than pytest's ugly stacktrace.

On top of that... I feel like parsing logs is going to become a real chore. Unless there's a ready-made library that can handle this for us, I'd be weary of going there.

**Comment by huguesdevimeux** [comment]
I agree, but if we could parse logs _before_ the output for example with a `logger` or `rich` option, it would be very good. 

> Other than that, if a comparison with == fails, we can output a prettier diff rather than pytest's ugly stacktrace.

Yes, we could do that, although it can quickly become a mess with all the regex.

**Comment by huguesdevimeux** [comment]
Closing in favour of #365
