### ISSUE TITLE
How to pass in other formula data without modifying the code

### ISSUE THREAD

**Issue by qywk99** [ManimCommunity/manim#3637]
## Description of proposed feature

> If you want to output different formulas, you can only modify the code, as shown below. This experience is too bad.

``` python3
text = r'\int_a^b f'(x) dx = f(b)- f(a)'
class Formula(Scene):
    def construct(self):
        t = MathTex(text)
        self.add(t)

# don't remove below command for run button to work
%manim -qm -v WARNING Formula
```

``` python3
text = r'\sin(x)'
class Formula(Scene):
    def construct(self):
        t = MathTex(text)
        self.add(t)

# don't remove below command for run button to work
%manim -qm -v WARNING Formula
```

## Additional comments

> Command line execution, unable to pass in other formula data

**Comment by uwezi** [comment]
While I don't really understand when it would be useful to have a LaTeX string provided via the commandline, it can be done right now using the command line argument handling of Python. There will be an error message produced, because Manim can usually be run with several scene names on the same command line, which then means that your equation will also be interpreted as a scene name...
Changing this behavior will disable the functionality to run several scenes insides a file from the same command - and this seems to be more useful than to dynamically pass additional scene arguments to any scene.

```py
import sys
class cmdline(Scene):
    def construct(self):
        eqn = MathTex(sys.argv[-1])
        self.add(eqn)
```

![bild](https://github.com/ManimCommunity/manim/assets/8582807/47b770b3-e7b5-4420-af32-e7c7ef923e53)

Yet another possibility is to get the equation through user input:

```py
class frominput(Scene):
    def construct(self):
        ans = input("enter your equation: ")
        eqn = MathTex(ans)
        self.add(eqn)
```

![bild](https://github.com/ManimCommunity/manim/assets/8582807/d21cd6bb-0a88-4af0-a627-602f74c061f7)

**Comment by uwezi** [comment]
And while the command line argument does not work in the Jupyter notebooks which you seem to be using, the `input()` version does

![bild](https://github.com/ManimCommunity/manim/assets/8582807/5d66ad39-c82d-454f-b139-3ffa8e1d1997)

Also in Jupyter notebooks - at least when using VSCode as editor - it is very easy to just copy and duplicate the complete cell in order to get a copy for your changed, new equation.

**Comment by qywk99** [comment]
thank you.
