### ISSUE TITLE
Improve the Helpless `Mobject.__repr__()`

### ISSUE THREAD

**Issue by HairlessVillager** [ManimCommunity/manim#3652]
## Description of proposed feature

I just be angry when I'm logging some `Mobject`s:
```python
logger = logging.getLogger(__name__)
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter("[%(levelname)s] %(lineno)d: %(msg)s"))
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)
info = logger.info
...

info(self.mobjects)
```
, the log looks like:
```text
[INFO] 184: [Line, Line, Line, Line, Line, Line, Line, Line, Dot, Dot, Dot, Dot, Dot, Dot, Dot, Dot, Dot]
```
, and I searched the [corresponding `__repr__()`](https://github.com/ManimCommunity/manim/blob/main/manim/mobject/mobject.py#L346):
```python
    def __repr__(self) -> str:
        return str(self.name)
```
, and I'm finally amused to annoyance.

imo It's helpless for programmers to debug, and not suitable for development.

## How can the new feature be used?

Well, I'm not sure whether a complex repr string is helpful or not.

According to [official documentation](https://docs.python.org/3/reference/datamodel.html#object.__repr__),

> If at all possible, this should look like a valid Python expression that could be used to recreate an object with the same value (given an appropriate environment). If this is not possible, a string of the form `<...some useful description...>` should be returned.

and Alex Martelli said on [Stackoverflow](https://stackoverflow.com/questions/1436703/what-is-the-difference-between-str-and-repr/1436756#1436756),

> ... and `__repr__` as unambiguous as you possibly can ...

this implementation may really poor.

However, this poor implementation exists when [manimlib was renamed to manim](https://github.com/ManimCommunity/manim/blob/b01936481b806561ab2a1af68212df1496cca0b8/manim/mobject/mobject.py#L50), and it has been like this for four years. If someone needs this feature midway, it should have been added long ago. But I couldn't even find the relevant issue, indicating that this feature may not be very important.

## Additional comments

I can't think of any way to make all Mobjects have the helpful repr function at a low cost. The subclasses of Mobject is everywhere, and it's naive to add a customized `__repr__` for every subclasses. Some black magics of Python may helpful, but my imagination is not rich enough😇.

"The best time to plant a tree was ten years ago. The second best time is now." If this feature is really useful, please add it as soon as possible.

**Comment by HairlessVillager** [comment]
I've read some source code, and I found that not all Mobjects has no helpful `__repr__()`.

I want to add a helpful repr function to some Mobjects, including at least Dot and Line. Can I do it?

**Comment by HairlessVillager** [comment]
The problem I encountered in this scenario is that the Line and Dot objects I needed were not rendered. Eventually, I realized that the problem was caused by my mistaken understanding of the length unit of objects in manim as pixels. In this scene, I expected `__repr__` to tell me:

- What are the start and end of the Line?
- What are the pos and radius of the Dot?

For example, compared to

```text
[INFO] 184: [Line, Dot]
```

, I am more inclined towards

```text
[INFO] 184: [<Line start=(xx, xx, xx) end=(xx, xx, xx)>, ..., <Dot pos=(xx, xx, xx) radius=xx>, ...]
```

Of course, this scenario is not abstract enough, and relying solely on this scenario cannot produce a sufficiently generic implementation. I haven't used manim for long, perhaps you can seek requirement from the community?

**Comment by MrDiver** [comment]
I would probably advise against making the reresentation more complex.
Especially for developing, because when you quickly want to log the contents of a list as you described in your example, then it would be a huge mess because even simpler scenes can generate tons of mobjects and having a readable output is very useful for that.

Additionally i would like to state that debuggers exist for that purpose and even if print debugging is a common practice if you run in to an issue where the print doesn't help you, you might as well try the debugger and drop yourself into a repl where you can inspect the objects without needing to print every single information that a mobject holds.

In the end Mobjects are way to complex to give a useful representation string, because the normal implementation would suggest that the object must be recreated by pasting the output in to the code and that would require A TON of output to make it useful.

So yes for small objects i agree this is useful in theory, but as far as actual practical usage, i do not see that being much of help except that people would want to add every single attribute in existence to every string output.

So if there is no compelling argument other than, i don't want to use a debugger or i don't want to print the attributes that i need manually, i do not really think this is worth the time and effort needed to maintain "useful" representation strings.

**Comment by HairlessVillager** [comment]
@MrDiver Thank you for your feedback! I have never considered using a debugger yet. If the debugger is more suitable for practical usage scenarios, there is indeed no need for further maintenance of the repr.

From the current situation, this is indeed a niche and replaceable demand. So I'm closing this issue now.
