### ISSUE TITLE
Link between reference and examples in docs

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#448]
At the moment, we have two big categories in the manim documentation:
#### B) the examples: https://manimce.readthedocs.io/en/latest/examples.html

As discussed in #445, it would be nice to insert Links between reference and examples.

One idea is that the reference shows one bare bone example on the reference page for this certain function that illustrates ONLY that particular feature. 
And in addition to that, there could be links to other example cases of this feature, which shows this function in a more realistic context. These other examples would be placed in the example section.
Matplotlib does this in a very similar way.
See here how they use that:
* Here is the reference, that points to corresponding examples:
https://matplotlib.org/api/_as_gen/matplotlib.pyplot.contourf.html
* And here is the example, that points to corresponding references:
https://matplotlib.org/gallery/images_contours_and_fields/contourf_hatching.html

**Comment by leotrs** [comment]
I like this! One thought is that if we are to do this in any sort of automated way, we should also allow the possibility for _not_ linking examples to the docstrings. The reason is that, for example, virtually every example is going to use either Scene.add or Scene.play, so the examples listing for them is just going to be bloated and pretty meaningless I think.

**Comment by behackl** [comment]
We need to decide on a relation between the examples section, the tutorials, and the reference manual.

In order to stick to a "single source of truth"-kind of paradigm for the documentation, I suggest to structure our documentation as follows:

- Rename "Examples" to "Example Gallery". This should contain a variety of different (*fancy*) examples that illustrate whan manim is capable of. Examples shoud -- and this is the main discussion of this issue -- link prominently to the corresponding classes in the reference manual.
- Host explanations / walkthroughs for entire modules in the module documentation (i.e., in the source code they would be in the module docstring).
- "Major" classes that users come in contact with often should all have at least one example illustrating how it is used. Most entries in the reference manual are extremely unhelpful when it comes to that.
- Guides that explain / introduce different manim concepts should be tutorials.

Whenever users use the "search box" in our documentation, pages from the reference manual are usually among the first few entries. This is why I think it is justified to have examples and illustrations in the reference manual as well.

**Comment by leotrs** [comment]
Points in favor of including examples in the source code as docstrings:
+ Docstrings these ship with the code and make debugging easier (IDEs can show docstrings).
+ They are available offline, regardless of whether the RTD site is up or even building.
+ The user will always have access to the documentation that was published at the same time the code was published. If the code changes in a later version, the documentation may change. This means that a user may find online the documentation for a version that is different than what they have installed.

Poinst against:
+ Including examples that render a video is semi-useless as docstring. It just won't have the same effect without the rendered image/video.

**Comment by leotrs** [comment]
Having said that, I am in favor of the following guidelines (please feel free to disagree/discuss):
+ Examples Gallery should aggressively link to the reference of every class that the example code touches.
+ If an example does not render image/video (e.g. if it's purely a logical example) then it should 100% be in the docstring and not in the Examples Gallery.
+ If a piece of documentation has a narrative and it's meant as an introduction or as a beginner resource, it should be a tutorial (docstrings *may* sometimes also have a narrative, but it's much more technical, not targeted necessarily to beginners, and much more succinct/dry: it's meant for people who know what they are looking for, and where they will find it).

**Comment by behackl** [comment]
Let us say that this is resolved for now. There is still more work to be done to make examples in the reference manual easier to find (in particular, @kolibril13 and I were discussing a complete "list of examples"), but I'll open a separate issue for that once the idea is clearer.
