### ISSUE TITLE
-fp does not work on Ubuntu 

### ISSUE THREAD

**Issue by huguesdevimeux** [ManimCommunity/manim#484]
On Ubuntu, when passing -f flag (open the file in file browser) and -p (preview) no preview is shown, only the file browser is open, instead of both. 

IIRC it is working on windows, as I remember having worked on this flag to make it work on Windows. 

Seems like an easy PR

**Comment by leotrs** [comment]
Thanks for reporting. I find it extremely weird that many flags seem to be failing lately. I was able to use -p only last week. There must be a PR that messed this up recently.

Another sign we need more tests. All the regressions are getting frustrating. We can't release v0.1 if -p can break at any point. I suggest we stop merging PRs without new tests added.

**Comment by huguesdevimeux** [comment]
Yes, but how do you want to test -p and -f ?

**Comment by leotrs** [comment]
They're two of the most used flags, no?

**Comment by huguesdevimeux** [comment]
Yes, I think so.

**Comment by naveen521kk** [comment]
Works for me on Windows. So it is only for Linux. For contributors, the below code needs to be fixed.
https://github.com/ManimCommunity/manim/blob/9271ca88936b4723415df20f9f87e01c108152a5/manim/utils/file_ops.py#L56-L72

**Comment by musabkilic** [comment]
I couldn't make -fp work in Windows either. The problem is, open_media_file runs *once* regardless if -f or -p or both of them are given at that time. (ofc doesn't run if neither is given)
https://github.com/ManimCommunity/manim/blob/97de34692de7442845f9b935c6d1481784a739d4/manim/__main__.py#L25-L43

If -f is set, open_media_file opens the folder.
https://github.com/ManimCommunity/manim/blob/9271ca88936b4723415df20f9f87e01c108152a5/manim/utils/file_ops.py#L56-L72
