### ISSUE TITLE
Info : Chocolatey GUI shows two versions of manim CE to install w/slight different names same ver. number

### ISSUE THREAD

**Issue by csrabak** [ManimCommunity/manim#494]
In Windows 10 64 bits the Chocolatey GUI shows two versions of manim whose descriptions are the same¹.

None of them installs successfully.

[1] OK, I didn't nit pick letter for letter. . .

**Comment by naveen521kk** [comment]
I know that. One would be `manim` and the other will be `manim.install`. Both eventually install the same for now. It has been done so that in future there can be a portable version of Manim(I thought of doing it but not yet done. Probably for the future.)

It's named correctly as in how meta-packages are named in chocolatey. Also, there should be info for that given in https://chocolatey.org/packages/manim.
![image](https://user-images.githubusercontent.com/49693820/94645304-224d1c80-0309-11eb-89a7-420d9425ab61.png)
