### ISSUE TITLE
More clarity of the use updater and ValueTracker

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#528]
There are now so many ways to update mobjects, and I am getting confused by it.
One thing that I really find strange is the dt parameter.
Here I have three examples of updaters:
https://manimce--526.org.readthedocs.build/en/526/examples/test.html

* Number 1 is working
```         
def my_updater(mobj,dt):
       mobj.shift(UP*0.01)
``` 

* Number 2 is not working (Only difference to 1: the dt parameter is removed)
```
 def my_updater(mobj):
      mobj.shift(UP*0.01)
```
* Number 3 is working again (Only difference to 2: a valuetracker is added)
```
v_tracker = ValueTracker(0)
def my_updater(mobj):
      mobj.shift(UP*0.01)
```
How do we want to get this more intuitive?
Maybe getting rid of the dt parameter in updater?

**Comment by leotrs** [comment]
Related to #321 

cc @nilaybhatia

**Comment by nilaybhatia** [comment]
TBH, I've never used the dt parameter till date. I am not sure what is it for. Whenever I have to use an updater, I refer to [this](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/a0444d693039be6ef2c1a2d94f58b85654c4ba17/English/update_successions/update_successions.py#L14).
I think `ValueTracker` is/was used along with an updater only in 2 scenarios:
1. You want to change the value of a displayed variable. Now, we added the `Variable` class which automatically does that internally.
2. Some visual property (like distance between points, angle between lines) needs to be updated continuously, like [here](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/a0444d693039be6ef2c1a2d94f58b85654c4ba17/English/update_successions/update_successions.py#L126). So now the question remains whether we can make the updater directly fetch the value of the Python variable and making all updates to the Python variable itself, rather than having to update the ValueTracker.
(Now I am beginning to think what is `ValueTracker` for 😆 )

**Comment by kilacoda** [comment]
```py
class Example2(Scene):
    def construct(self):
        def my_updater(mobj):
            mobj.shift(UP*0.01)
        circ_reference = Circle().set_color(WHITE)
        tri = Triangle().set_color(RED)
        self.add(circ_reference, tri)
        self.wait(0.5)
        tri.add_updater(my_updater)
        self.wait(2)
```

This is the code from the second example. I think you need to `self.add(tri)` after `tri.add_updater`. See [this ToB video](https://www.youtube.com/watch?v=l4B7IH1D1uI&t=179s) .

**Comment by leotrs** [comment]
#752 will close this.

**Comment by behackl** [comment]
At the time being, there are time-based and non-time-based updaters, and the distinction (occasionally) makes sense. I think the clarity regarding which type of updater to use when would improve by cleanly separating their interfaces, #321 -- and one issue is enough to track this, so I propose closing this one.
