### ISSUE TITLE
Make Positioning Related to Tex More Consistent

### ISSUE THREAD

**Issue by sudgy** [ManimCommunity/manim#540]
Consider the following two images:

```python
class HigherDot(Scene):
    def construct(self):
        text = Tex("Aa")
        dot = Dot()
        dot.next_to(text, RIGHT)
        self.add(text, dot)
class LowerDot(Scene):
    def construct(self):
        text = Tex("ga")
        dot = Dot()
        dot.next_to(text, RIGHT)
        self.add(text, dot)
```

`HigherDot`:
![HigherDot](https://user-images.githubusercontent.com/20936595/95800190-a8734680-0cab-11eb-8784-4bffc15373f5.png)

`LowerDot`:
![LowerDot](https://user-images.githubusercontent.com/20936595/95800202-b1641800-0cab-11eb-976b-34a7b66961f8.png)

You can see that the dot is aligned differently relative to the "a" because the top and bottom of each `Tex` object is different.  I feel like there needs to be some way of consistently positioning things relative to (`Math`)`Tex` objects.  I can't think of any simple way to do it, but I still feel like it should be done somehow.

**Comment by leotrs** [comment]
Thanks for reporting. I agree this unpredictable behavior is annoying. In general this sounds like a very very hard thing to pull off since we would have to control how Tex objects are rendered. cc @cobordism

**Comment by cobordism** [comment]
I fear this isn't possible.
When we compile the tex and import it to manim as SVGs, we just have a bunch of paths... and there is no way for the "ga" bit to know how high an "A" would have been. The next_to command only know the top, bottom, left edge, right edge, and center of the shape "ga".

But on the other hand, this all feels backward to me in a sense. TeX is the most powerful typesetting engine we have. Why render two pieces individually and then try to typeset them in python by hand? Why not use TeX? There's \bullet and \cdot and there's \textbullet and \centerdot and \medbulley and \sqbullet and \smallblackcircle and ... (and that "..." is \ldots btw).

The point is: let latex to what latex does best. typesetting.
Try maybe

tex = Tex("ga", "$\bullet$") 
and
tex = Tex("Aa", "$\bullet$") 

you can even follow this with
text = tex[0]
dot = tex[1]

and continue on from there exactly as before.

complete list of latex symbols:
http://mirrors.ctan.org/info/symbols/comprehensive/symbols-a4.pdf

**Comment by cobordism** [comment]
> a more complicated shape that TeX couldn't handle.
I contend that such a thing does not exist :D
(after all, you can use tikz within a tex document) ... but ok. 

>use the positioning of that x to figure out how to position other things
Tex of course has things like this. To affect spacing, you can place virtual elements anywhere by using `\phantom{x}`. Or maybe even just `\vphantom{x}` when only the height counts.... 
...but none of that helps us as these characters are not rendered and thus do not show up in the svg that manim imports.

So what could we do?
There are ways to save the position of various objects in tex output: https://tex.stackexchange.com/questions/119269/determining-the-position-of-a-symbol-letter-in-coordinates but this will not be useful for us. 
**After we leave the world of latex and import the svg into manim, we no longer have text, we have graphics;** and you want to do text alignment on graphics. Unless dvisvgm has some magic powers I don't know about, I don't know how we might keep text alignment information through to the svg stage.

I really hesitate to render every line with an extra `x` because this can have so many side effects on layout, spacing, line breaks, ...

Perhaps some situations do require alignment by hand - and we should just document it better?
You could just replace 
```
        dot.next_to(text, RIGHT)
```
with 
``` 
       dot.next_to(text[0][1], RIGHT)
```
 to align the dot to the center of the `a`.

Or you could align the bottom of the dot to the bottom of the `a` in your examples by typing
```
        text = Tex("Aa")
        dot = Dot()
        dot.set_y(text[0][1].get_y(direction=DOWN), direction=DOWN)
```

**Comment by leotrs** [comment]
> You could just replace
> 
> ```
>         dot.next_to(text, RIGHT)
> ```
> 
> with
> 
> ```
>        dot.next_to(text[0][1], RIGHT)
> ```
> 
> to align the dot to the center of the `a`.
> 
> Or you could align the bottom of the dot to the bottom of the `a` in your examples by typing
> 
> ```
>         text = Tex("Aa")
>         dot = Dot()
>         dot.set_y(text[0][1].get_y(direction=DOWN), direction=DOWN)
> ```

I tend to agree this cannot be done in general. I do like these workarounds though, we should document them somehow.

**Comment by sudgy** [comment]
LaTeX has a `\write` command to write to the log file.  Is there any way of using that to output coordinates?

**Comment by cobordism** [comment]
> LaTeX has a `\write` command to write to the log file. Is there any way of using that to output coordinates?

I fear it would be a very complicated task to write out those coordinates, read them, parse them, translate them into something meaningful in manim units ...
My hunch is that you'd be better off rewriting the manim svg parser entirely so that it can understand svg files with embedded fonts; which in turn allows us to then remove the `-n` flag to dvisvgm ... and then the TeX() mobjects would no longer be 'just paths'.

**Comment by cobordism** [comment]
I will tag this as 'wontfix' because there is nothing we can do until SVG handling has been rewritten.
Until then you'd need to either use LaTeX for alignment, or mess around by hand. (see comments above)
