### ISSUE TITLE
Make it easier to change background colour.

### ISSUE THREAD

**Issue by cobordism** [ManimCommunity/manim#604]
**Describe the bug**
Right now I can only change the background colour in my source file by writing
`config["background_color"] = WHITE` for example.

The problem is that this works only for one scene. If I write
```
config["background_color"] = WHITE
...Scene1...

config["background_color"] = BLUE
...Scene2...
```
then Scene1 will render with blue background.

**Expected behavior**
Something as prominent and important as the background colour of a scene should be easier to change, and more importantly should be changable from within a scene.
I am asking for
```
self.play(Animation1)
self.background_color=Blue
self.play(Animation2)
self.background_color=Green
self.play(Animation3)
```

**Comment by leotrs** [comment]
I agree this should be supported. However, the current architecture is not going to allow for it. Because of two reasons.

### Reason 1
`manim/__main__.py` executes the whole module before rendering the scene. To side-step this, you could use your own script instead of calling manim from the CLI:
```
class Scene1():
    ...

class Scene2():
    ...

if __name__ == '__main__':
    config["background_color"] = WHITE
    s1 = Scene1()
    s1.render()
    config["background_color"] = BLUE
    s2 = Scene2()
    s2.render()
```

This is definitely not ideal, but can serve as temporary workaround.


### The config dict is global
The *actual* problem though is that the config is global. I am not opposed to making it not global and have each Scene contain its own config. But this is a major change that will require a bit of refactoring and testing. At the very least, every mobject will have to contain a reference to its parent scene so they can access the Scene's specific config. Which is not bad, but it will increase the overhead in general.

We should come back to this after #620 is merged.

**Comment by behackl** [comment]
Maybe this approach is a bit naive, and maybe there is a better way to do things currently -- but if we would add a property `background_color` to `Scene` like

```py
class Scene(Container):
    [...]

    @property
    def background_color(self):
        return self.renderer.camera.background_color

    @background_color.setter
    def background_color(self, color):
        self.renderer.camera.background_color = color
        self.renderer.camera.init_background()

```
then the background color can be set just as suggested above, via `self.background_color = GREEN` etc. -- and for simple test cases, this produced correct output for me.

But then again, I'm still not that deep into the camera and renderer; this might not be a very practical approach.

**Comment by leotrs** [comment]
This is the right way of doing it. I thought about this at some point and forgot to update this issue. Thanks for trying it out.

For now, we can just do self.renderer.camera.backgorund_color = GREEN. But I agree we could perhaps add a new property as @behackl suggests.

**Comment by leotrs** [comment]
Uhm also another alternative is to just do

```python
class Scene():
    @property
    def camera(self):
        return self.renderer.camera
```

and call it a day?

**Comment by behackl** [comment]
I really don't mind too much whether it is `self.camera.background_color = ...` or `self.background_color = ...` (the former might actually be cleaner, true) -- but without the setter calling `self.renderer.camera.init_background()`, it would not work for me.

**Comment by behackl** [comment]
After thinking for another minute, I think the cleanest solution would be to add `background_color` as a parameter to `Camera` whose setter knows to run `init_background`, and then possibly have the `camera` property you suggest for `Scene`. :-)

**Comment by leotrs** [comment]
Well. The *true* solution is to get rid of `Camera.CONFIG`, which would immediately put `background_color` in the constructor of `Camera`. But we know how that goes.
