### ISSUE TITLE
We need a devops team

### ISSUE THREAD

**Issue by leotrs** [ManimCommunity/manim#622]
As the project grows in collaborators and our assets grow in number, we need to designate a team (or individual persons) to a bunch of tasks that will need taken care of

1. different tasks related to maintaining our landing page [manim.community](http://manim.community)
2. general managing of releasing and packaging
3. maintaining our CI procedures

If you think of other devops-like tasks, please edit this comment and add it.

If you'd like to take on these tasks, please say so!

cc @cobordism @behackl @eulertour @naveen521kk @huguesdevimeux

**Comment by cobordism** [comment]
> If you think of other devops-like tasks, please edit this comment and add it.

Other tasks that I'd classify as devops:

Maintaining DNS for manim.community (CNAME and A records for www, docs, etc, MX records for mail ...)
Discord server settings - maintaining channels and policies, and permissions, but also bots
Github.com settings - teams and permissions and extensions and webhooks
Onboarding new members (in terms of permissions) as well as removing old accounts.

**Comment by huguesdevimeux** [comment]
The best I can do is Discord, and maybe gitHub.
Otherwise, I either don't have the proper knowledge or can't at the moment take any long time commitement required by some of these tasks.

**Comment by eulertour** [comment]
Although a dedicated team would be nice, I think the best we can manage at this point is to have clear procedures in place for devops-related tasks and to automate as much of the process as possible. In that sense I think the main focus should be to simplify and when necessary document these tasks.

It's also worth stressing here that since we don't have as much time to dedicate to them, it's important to eliminate complexity in devops tasks as much as possible.

**Comment by leotrs** [comment]
All fair points - now we just need to assign some people to some tasks :)

**Comment by cobordism** [comment]
> Although a dedicated team would be nice, I think the best we can manage at this point is to have clear procedures in place for devops-related tasks and to automate as much of the process as possible. 

I think we are basically in agreement. My suggestion was not against automation (indeed that is an integral part of devops) but for making an explicit group of people responsible for it. Automation is great, but if something breaks, who you gonna call? 

Whoever ends up on team-devops, one of the things they must do is manage credentials so that, even if one of them is unavailable, the others can jump in and fix things. They must manage access keys, passwords, and credentials. And yes, document everything.

**Comment by leotrs** [comment]
This issue doesn't have a clear follow-up or TODO item. So in the interest of moving things forward, here is a list of current people who have chosen to do (or who have found themselves being assigned to) devops-y things:


- manim.community website @cobordism, @behackl 
- general managing of releasing and packaging @eulertour
- maintaining our CI procedures @naveen521kk 
- Discord server settings @behackl @leotrs @eulertour @PgBiel 
- Github.com settings @eulertour @leotrs 
- **Onboarding new members (in terms of permissions) as well as removing old accounts.** no one assigned here yet

This is of course off the top of my head. Feel free to edit this comment to expand or amend this list.

Once we have a clear picture of devops assignments, we can discuss responsibilities and then close this issue.

**Comment by behackl** [comment]
Things are running more or less smoothly, I think this generic issue can be closed.
