### ISSUE TITLE
Failed to build pycairo ubuntu 16.04

### ISSUE THREAD

**Issue by abdelrahman-emam** [ManimCommunity/manim#675]
I tried to install manim using
`pip install manimce`

and I got this error 
`Failed to build pycairo`

Then I tried to install pycairo (cairo) manually and it got installed using
`pip install https://github.com/pygobject/pycairo/releases/download/v1.13.2/pycairo-1.13.2.tar.gz`

And now I can import cairo when I launch python in the terminal successfully, but I still get the same error Failed to build pycairo when I try to install manim again

Here's the full log

```pip3.7 install https://files.pythonhosted.org/packages/9d/6e/499d6a6db416eb3cd
f0e57762a269908e4ab6638a75a90972afc34885b91/pycairo-1.20.0.tar.gz
Collecting https://files.pythonhosted.org/packages/9d/6e/499d6a6db416eb3cdf0e57762a269908e4ab6638a75a90972afc34885b91/pycairo-1.20.0.tar.gz
  Using cached pycairo-1.20.0.tar.gz (344 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: pycairo
  Building wheel for pycairo (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/abdelrahman/virtualenvironment/workshop/bin/python /home/abdelrahman/virtualenvironment/workshop/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmphj2o2s09
       cwd: /tmp/pip-req-build-racsx_6a
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/cairo
  copying cairo/__init__.py -> build/lib.linux-x86_64-3.7/cairo
  copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.7/cairo
  copying cairo/py.typed -> build/lib.linux-x86_64-3.7/cairo
  running build_ext
  Requested 'cairo >= 1.15.10' but version of cairo is 1.14.6
  Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pycairo
Failed to build pycairo
ERROR: Could not build wheels for pycairo which use PEP 517 and cannot be installed directly
```

I'm using ubuntu 16.04 with python 3.7 installed seperately on virtual env. I am using

**Comment by behackl** [comment]
Thank you for your report.

The issue here is a version mismatch: the version of the cairo library you installed via the package libcairo2-dev is too old for the version of pycairo requested by manimce. I see two possible paths forward:

- Option 1: try to upgrade your system package. (Which might turn out really inconvenient, and I am not sure there is a clean solution for that other than upgrading your version of Ubuntu.)
- Option 2: Try to see whether you can install all other dependencies manually (have a look at the list in https://github.com/ManimCommunity/manim/blob/14bfaab0a9296a88ca39b38e210cf2dd552ee532/pyproject.toml) and then use pip install --no-dependencies manimce. There is no guarantee that this will work, but I'd be somewhat optimistic.

In case you have some experience with docker, you might want to check out https://hub.docker.com/r/manimcommunity/manim to save you the trouble of getting everything to run locally.

**Comment by abdelrahman-emam** [comment]
Thank you, Unfortunately I don't have experience with docker, but I will try the second option indeed.

**Comment by ucalyptus** [comment]
@abdelrahman-emam I face this issue 
```
ModuleNotFoundError: No module named 'pangocairocffi._generated.ffi'

```

**Comment by behackl** [comment]
> @abdelrahman-emam I face this issue
> 
> ```
> ModuleNotFoundError: No module named 'pangocairocffi._generated.ffi'
> ```

See https://docs.manim.community/en/latest/installation/troubleshooting.html

**Comment by ucalyptus** [comment]
Thanks @behackl , solved!

**Comment by behackl** [comment]
@naveen521kk can you think of a way to allow older versions of pycairo (and thus the version of libcairo installed on the system) in situations where wheels are not required?

If so, we should think about supporting Ubuntu 16.04 again with our next release.

Otherwise, there is nothing left to do here.

**Comment by naveen521kk** [comment]
`1.19.*` can be used I think. Because the required version there is `1.13.1`. Small edit in pyproject.toml can make it work. It should be `>=1.19.0` then.
