### ISSUE TITLE
FunctionGraph is not used anywhere

### ISSUE THREAD

**Issue by protonlaser91** [ManimCommunity/manim#782]
## Enhancement proposal

Title pretty much says it all.
I only found one use of it and that was in building_blocks.rst and it's only being used as an example (Could be replaced with ParametricFunction). Can prepare a PR to deprecate it if there really is no use for it.

**Comment by leotrs** [comment]
Hi @protonlaser91 and thanks for bringing this up.

There are many classes that are not used or mentioned in the codebase. This does not necessarily mean they are useless. It might mean that they are user-facing: meant to be used by end-users and not by devs. So even if a class is not mentioned anywhere else, it may still be a good idea to keep it around in case users want to use it.

Having said that, I have _no idea_ what the intended purpose is of this class. Do you know more about it? This sounds like a good candidate to actually deprecate. Could you tell us if each usage of this class can be superseded by using ParametricFunction instead? If so, we can indeed deprecate it. If, on the contrary, it has some other usage, then the way to go is to document it rather than deprecate it :slightly_smiling_face:

**Comment by protonlaser91** [comment]
Hi! I was thinking a potential use of this class would be in the method get_graph, but that method explicitly uses ParametricFunction when it seems that FunctionGraph was built exactly for that purpose. That's why I feel it is obselete. I think in any case where a FunctionGraph could be used, a ParametricFunction can do the same job or better.

**Comment by Aathish04** [comment]
tl;wr: ParametricFunctions are more versatile, but FunctionGraphs are easier to use. 

A `FunctionGraph` takes an explicit function in x, while a `ParametricFunction takes`, well, a Parametric Function.

You can use a FunctionGraph in scenes that aren't GraphScenes, so there's an advantage in that (though you _could_ just use `ParametricFunction` and just keep one direction as as `LEFT*t`

I think it just boils down to convenience. If I want to graph an explicit function in x, I'll turn to `FunctionGraph`. If I want more control, I'll probably use ParametricFunction.

**Comment by protonlaser91** [comment]
Sure, I can remove the deprecation label from my pull request

**Comment by leotrs** [comment]
@protonlaser91 could you please either (a) update the title of this issue to better reflect your intent, or (b) close it?
