### ISSUE TITLE
Running manim without terminal

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#829]
At the moment, it is already possible to run manim without the terminal, e.g. with this script:

```py
import matplotlib.pyplot as plt
from manim import *

class Example(Scene):
    def construct(self):
        circle = Circle()
        self.add(circle)
        self.wait()

scene = Example()
scene.render()
data = scene.renderer.get_frame()
plt.imshow(data)
plt.show()
```
I think this has two drawbacks over running manim the classical way with the terminal:
1. It is not yet possible to read a custom manim.cfg file
2. It is not yet possible to use the preview flag -p from the comment line, that is why I currently used matplotlib. 

@leotrs : as you are the one most familiar with the config system, do you think that this is easy to implement?

**Comment by leotrs** [comment]
I have to say that in general, I am against using manim without the command line. I would be more favorable toward a recent idea by @naveen521kk in #805 to keep simplifying the command line interface.

> 1. It is not yet possible to read a custom manim.cfg file

This has been possible for a while. [Read the docs](https://docs.manim.community/en/latest/reference/manim._config.utils.ManimConfig.html#manim._config.utils.ManimConfig.digest_file).

> 2. It is not yet possible to use the preview flag -p from the comment line, that is why I currently used matplotlib.

I am against implementing the preview flag in this way. The reason is that the preview flag has nothing to do with manim itself and it just asks another application to run a file created by manim. This is what the command line command is important: to _interface_ between manim and other applications. I could be in favor of implementing something like `Scene.preview()` or `Scene.show()`, but I honestly don't think that's necessary.

**Comment by Hari-07** [comment]
What about making a full GUI for manim? Maybe as a GSOC Projecy

**Comment by leotrs** [comment]
@Hari-07 there are indeed some projects in the works about that.

**Comment by leotrs** [comment]
@kolibril13 would you please update this issue with a more concrete action item? The first item you mention is already possible. I am against implementing the second one. If others feel the same way then we can close this.

**Comment by Hari-07** [comment]
> @Hari-07 there are indeed some projects in the works about that.

@leotrs like? Can you give some links... That seems very interesting work

**Comment by leotrs** [comment]
You should probably start by reading the documentation on the main manim classes https://docs.manim.community/en/latest/

**Comment by kolibril13** [comment]
Sorry for opening this issue and then abandoning it.
Thanks for pointing this out with config file!
And I agree that the preview feature does not really need to be part of the core lib.
