### ISSUE TITLE
Axes class no longer sets x_min, x_max, y_min, y_max values to self.x_min, self.x_max, self.y_min and self.y_max respectively.

### ISSUE THREAD

**Issue by Ammar34** [ManimCommunity/manim#840]
## Description of bug / unexpected behavior

When Axes class instance is created with kwargs ->`` x_min``, ``x_max``, ``y_min``,`` y_max``, they are not shown in the generated Axes animation.
This issue arose after migration from dictionaries.
P.S. I have also started getting a warning "Creating a dummy animation" which if I am right is because animation receives mobject as None.

## Expected behavior

Previoulsy, it worked just fine. Thus, setting these kwargs to ``self.x_min``, ``self.x_max``, ``self.y_min`` and ``self.y_max`` was expected.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
from manim import *


class AxesExample(Scene):
    def construct(self):
        axes1 = Axes(
            x_min = 0,
            x_max = 5,
            y_min = -1,
            y_max = 1,
            axis_config = {
                "include_numbers": True,
                "include_tip" : False,
                "decimal_number_config" : {"num_decimal_places": 1, "color": LIGHT_GREY}
            },
            x_axis_config={
                # "x_min" : 0,
                # "x_max":5,
                "numbers_to_show": np.arange(1,6)
                },
            y_axis_config={
                # "y_min" : 0,
                # "y_max":5,
                "numbers_to_show": np.arange(-1,2)
                }
            )
        # axes1.stretch_to_fit_width(4)
        # axes1.stretch_to_fit_height(3)
        self.play(ShowCreation(axes1))
        self.wait()
        graph = axes1.get_graph(lambda x:np.sinc(x), x_min = 0, x_max = 5, color = RED)
        self.play(ShowCreation(graph))
        self.wait()
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

![image](https://user-images.githubusercontent.com/12208432/101323653-e1363300-388a-11eb-83f3-18be0432d08e.png)

</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments

It seems to be that the ``CoordinateSystem`` class is not able to find the ``"x_min"``, ``"x_max"``, ``"y_min"`` and ``"y_max"`` attributes in self thereby setting the ``self.x_min``, ``self.x_max``, ``self.y_min`` and ``self.y_max`` to the dimensions of the frame.

https://github.com/ManimCommunity/manim/blob/62f0147f8135e68323fd2a2a2f8258772faa8c9f/manim/mobject/coordinate_systems.py#L132-L148

https://github.com/ManimCommunity/manim/blob/62f0147f8135e68323fd2a2a2f8258772faa8c9f/manim/mobject/coordinate_systems.py#L26-L40

**Comment by Ammar34** [comment]
A quick print of the ``new_config`` dictionary showed that these values are indeed not set to the arguments passed.
https://github.com/ManimCommunity/manim/blob/62f0147f8135e68323fd2a2a2f8258772faa8c9f/manim/mobject/coordinate_systems.py#L157-L163

![image](https://user-images.githubusercontent.com/12208432/101326187-b8b03800-388e-11eb-9430-ad98bd876c91.png)

**Comment by cobordism** [comment]
I see the issue.
This indeed looks like it was part of the digest_configs mess.
Thus the `__init__` function of `CoordinateSystem` doesn't accept things like `x_min` as keyword arguments, but instead looks if the attributes `self.x_min` exists. With the `digest_config` system as it was, the keyword argument `x_min`, no matter where it was given, would lead to the attribute being set. No we have to pass the arguments explicitly.

**To fix this issue:**
We should add *kwargs to line 153 of coordinate_systems.py (the call to the `CoordinateSystem.__init__`) and change the `__init__` to accept these keyword arguments.
**To avoid breaking anything else with this fix:**
 Further we have to change `ThreeDAxes` (line 231) so that the relevant arguments are passed "upstairs", and we should check that no other class in this file also sets `x_min` for itself without passing the keyword to the parent.


**To clean up further:**
We should probably refactor the `create_axis` function too - there is too much merging of dicts going on for my taste. Perhaps a more thorough redesign of how to configure axes is also called for. However that can be a subsequent PR.

**Comment by Ammar34** [comment]
I am already working on a solution that makes the whole axes class a little better. My solution involves creating these attributes within the axes class and then assigning the keyword arguments passed directly to the Axes class or from the x_axis_config and y_axis_config dicts. While working I noticed a number of issues with Axes Class and now in the process of fixing them. I am almost done. I will PR once ready.

**Comment by cobordism** [comment]
cool. awesome.
thanks for working on this.

My feeling is that it is best to have one canonical place where the attributes are set. Thus I think I prefer to accept the `x_min` keyword in `Axes` and other classes, (or accepting an `x_axis_config` from which we can calculate `x_min`) but then passing that "upstairs" as a keyword argument and only there setting it as an object attribute. Rather than just checking if the attribute has been set somewhere else - as the code is doing now.

So CoordinateSytem would take an `x_min=None` and then check: `if x_min is None: x_min = -config["frame_x_radius"]` and then `self.x_min = x_min`. 
The child classes would just pass `x_min = x_min_value` up to the parent.

All this will help us further untangle where which attributes are set and aid us in the general cleanup and refactoring that is planned to happen next.

but I am open to other solutions too. looking forward to you PR.

**Comment by Ammar34** [comment]
I agree. I will see what I can do with the suggestions you provided @cobordism.
