### ISSUE TITLE
TextMobject is not working in Jupyter

### ISSUE THREAD

**Issue by Viasis** [ManimCommunity/manim#847]
## Description of bug / unexpected behavior

I'm currently new to manim and I've encountered a problem whenever I try to use the syntax "TextMobject" but its working fine with "TexMobject" instead. 

## How to reproduce the issue

<details><summary>Problem occurs when i use TextMobject</summary>

```py
class Textcolor(Scene):
    def construct(self):
        text= TextMobject("Hello World")
        
        self.play(Write(text))
        self.wait()
```
but it works when i do

```py
class Textcolor(Scene):
    def construct(self):
        text= TexMobject("Hello World")
        
        self.play(Write(text))
        self.wait()
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "D:\Anaconda\lib\site-packages\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "C:\Users\Kaimun\AppData\Local\Temp\tmpjyck_vmk.py", line 48, in construct
    text= TextMobject("A","B","C","D","E","F")
  File "D:\Anaconda\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 150, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "D:\Anaconda\lib\site-packages\manimlib\mobject\svg\tex_mobject.py", line 190, in break_up_by_substrings
    sub_tex_mob.submobjects = [VectorizedPoint()]
IndexError: list index out of range
```

</details>

## System specifications

<details><summary>System Details</summary>

```
- OS (with version, e.g Windows 10 
- RAM: 16gb DDR4
- Python version 3.9:
```
</details>

<details><summary>LaTeX details</summary>

+ MikeTex
+ Installed LaTeX packages:
biber
bibtex
doc
dvipdfm
dvipdfm
dvirps
fontconfig
fonts
ghostscript
hunspell
makeindex
metafont
metapost
miktex
pdftex
scripts
source
text
tex
tex4ht
tpm

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments

Tried surfing github for similar problems but couldnt find any. Am new to the Github community so pardon my ignorance!

**Comment by leotrs** [comment]
Hello @Viasis. Are you using the latest version of manim CE? If so, the TextMobject and TexMobject classes have been replaced. TextMobject has been deprecated in favour of Tex. TexMobject has been deprecated in favour of MathTex. Can you try using these classes again and seeing if that works? Thanks!

**Comment by Viasis** [comment]
Thanks for the reply @leotrs ! I downloaded the manim package through the anaconda prompt so its the latest package i think. I'll try your recommendation, thank you!

**Comment by Viasis** [comment]
@leotrs To clarify I will have to replace "TextMobject" with "Tex" am I right?

**Comment by Ammar34** [comment]
Thats right.
``TextMobject`` -> ``Tex``
``TexMobject`` -> ``MathTex``

**Comment by Viasis** [comment]
@Ammar34 It says that neither Tex nor MathTex is defined. How do i check if im running on the latest version of manim?

**Comment by Ammar34** [comment]
From your Terminal output it seems like you are using 3b1b version of manim. The manimlib folder has long been removed from community version. Are you sure you didn't want to post this issue here https://github.com/3b1b/manim/issues
If not, then I suggest you reinstall manim community
P.S Manim CE has still support for TextMobject and TexMobject (for backwards compatibility I presume) so this error shouldn't have occured with community version.

**Comment by Viasis** [comment]
@Ammar34 Oh i didnt know that i was using the 3b1b version. I just typed "python3 -m pip install" in the anaconda prompt. I will install the community one right now thanks!

**Comment by Viasis** [comment]
I've installed the community version of manim, but i have a little trouble using it from Jupyter instead. If the manimlib folder has been removed from the community version, how do i import the manim folder onto Jupyter

**Comment by Ammar34** [comment]
If added to path (you should check in environment variables) you can simply type ``from manim import *`` in your .py file before writing your code

**Comment by Viasis** [comment]
I did as instructed by adding the manim folder into environment variables and replacing

```
from manimlib.imports import *

```
to
```
from manim import *
```

But it shows a new error right now 
```
D:\Anaconda\lib\site-packages\jupyter_manim\__init__.py:297: UserWarning: Could not find path in the manim output
  warn('Could not find path in the manim output')
```

My code is as follows,

```
%%manim 

from manim import *

class hi(Scene):
    def construct(self):
        text=Tex("hi")
        self.play(Write(text))
        self.wait()

```

**Comment by Ammar34** [comment]
Can I ask which application are you using to write your code?
Examples: VSCode, PyCharm, Spyder, JupyterLab

**Comment by Ammar34** [comment]
Okay I got it working. Try the following steps. (I suggest you start from scratch)

1.  Install all dependencies mentioned [here ](https://docs.manim.community/en/latest/installation.html#installing-dependencies)(install pango, FFmpeg, LaTex except for choco and installing manim from there). Dont forget to add to ``PATH``

2.  Launch Terminal and enter the following commands (I assume you have added anaconda to ``PATH``. Typing ``conda --version`` should give you something like ``conda 4.9.2`` )
 

-  Create you environment using ``conda create --name ManimCE``

-  Activate the environment using ``conda activate ManimCE``

- Since conda does not have manimce package just yet (I dont know if there are any plans for this). So you take advantage of the good old `pip`. For that you need to install and if necessary upgrade to the latest version. Type ``conda install pip`` (If you already have pip installed, it might ask you to update).  Once installed, you can install community edition directly using ``pip install manimce`` or ``pip install manim``

- Finally open a folder of your liking in your favourite IDE and select the python interpreter (``python 3.8.5 64 bit conda`` in my case).  Create you test file:

```py
from manim import *

class test(Scene):
    def construct(self):
        someText = MathTex("Hello!")
        self.play(ShowCreation(someText))

```

### Output

![image](https://user-images.githubusercontent.com/12208432/101752820-c1557800-3af3-11eb-8916-b6b18f923c2f.png)

### Further Comments
If you still come across any error in setting up manim CE, leave a comment.

**Comment by Viasis** [comment]
Im currently using JupyterLab right now!! I've done as instructed, installing the various dependencies using the anaconda powershell and adding the files into path. But when I run the terminal using your code, nothing seems to show up. 

![Capture](https://user-images.githubusercontent.com/75681028/101790120-0d78da80-3b3d-11eb-9236-5058edc55116.PNG)


Initially i had to include a line of code like to make the code work but now do not have it, could that be the problem? 

```
%%manim Shapes

```

Even if i was to include the following line of code it will just output the same error which is 
```
Media will be written to ./media\. You can change this behavior with the --media_dir flag.

   There are no scenes inside that module
```

My only concern is that i worry that i might have installed the wrong thing and added the wrong thing to path. As of now these are the things in my path 

![123](https://user-images.githubusercontent.com/75681028/101790432-65174600-3b3d-11eb-9f69-a195a3c99360.PNG)

Sorry for the trouble, i feel like a huge burden...

**Comment by leotrs** [comment]
No burden at all! This is why we have a community :slightly_smiling_face: If you would like some more interactive help, you can also try our discord server.

PS I believe @PgBiel has experience with getting manim running in notebooks.

**Comment by Viasis** [comment]
thank you @leotrs !! @PgBiel may i ask how did u install manim on jupyter (lab or notebook)? Would appreciate your help!! I've been trying to fix this problem for the past 2 weeks.

**Comment by kolibril13** [comment]
@Viasis : we are currently implementing the jupyter support for manim-community.
As soon as it is ready, you will find it here:
https://docs.manim.community/en/latest/changelog.html
Or at https://twitter.com/manim_community
It will be there in approx 1-3 months.
Closing this issue for now, feel free to reopen it if you still have questions.
