### ISSUE TITLE
Remove OpenCV and SceneFromVideo

### ISSUE THREAD

**Issue by PgBiel** [ManimCommunity/manim#85]
opencv does not seem to be used anywhere other than in ScenefromVideo, which seems to be broken.

**Comment by leotrs** [comment]
I vote we 100% scrap this file and opencv. Not only because it's broken but because this file is actually trying to use manim in a way that it's not intended. It seems like an awesome project to be honest, but I don't think it belongs inside manim itself. In the future, if anyone wants to work on this, I think it should live inside the ManimCommunity organization, but in a separate repo than manim itself.
